### ISSUE TITLE
Strange bug with fields

### ISSUE THREAD

**Issue by alexstanbury** [MoonStorm/trNgGrid#103]
http://plnkr.co/edit/2asCVhLN61OgkWkCsT44?p=preview

Here are the issues:

I am showing the first 6 fields of 12 by default by binding to the fields attribute, if I change the fields to show the last 6 fields, no data is displayed. However, if I change the fields to show 5 or less (of any combination) it works. 

If I change to show 5 fields (7-11), then change to show the last 6 fields (7-12), then 7-11 show but field 12 still does not.  

Everything works as expected if I do not restrict what fields are shown on first load by removing the call to $scope.reset. 

I just tested and this also happens when there are only 4 fields, start with 1+2, try and show 3+4 - breaks, show just 3 - works. I presume it will happen with any number of fields.

**Comment by MoonStorm** [comment]
Seems to be fixed in the current version. No idea why!?! :smile:
