### ISSUE TITLE
Accessing an array of objects within the gridItem.

### ISSUE THREAD

**Issue by AJCraddock** [MoonStorm/trNgGrid#106]
Let me first start off by saying this is an awesome project, and kudos for making something that works and is easy to use. :+1: 

Now my issue is, I am attempting to to create a grid that takes an array of objects that is contained within each "gridItem" and display each object in the array in its own separate column. I also need these columns to be sortable. Is trNgGrid capable of doing such a thing. 

[Here](http://jsfiddle.net/pkuca2f8/26/) is a link to a fiddle I made from your "simple example" fiddle. The most important part of this demo would probably be the way the object is set up. It closely resembles the object I am trying to display. The desired result for the fiddle would be: there are 6 columns.

name | age |neighborhood 1| neighborhood 2 | neighborhood 3 | neighborhood 4
--------|-------|-----------------------|-----------------------|-----------------------|----------------------
Enos|99|rge|dre|ndf|tbd
side/note: The fieldName on the array object is more so for reference but it would be good if you could enlighten me on some way to tie that to the header.

Thank you for ANY assistance you can provide in this matter.

**Comment by MoonStorm** [comment]
Sorry for the late response. I'm in the process of moving house. 
For the time being ``ng-repeat`` does not work. See #91 for a discussion on this subject.
