### ISSUE TITLE
Sorting in IE9

### ISSUE THREAD

**Issue by fabriciolemos** [MoonStorm/trNgGrid#108]
In IE9,  clicking the column heading text does not trigger the sort. Clicking just above, just below, or to the side of the text triggers the sort.

When you click in the column heading text, the `<div class="tr-ng-title ng-binding">` is select, but the `<div title="Sort" class="tr-ng-sort" ng-click="toggleSorting(columnOptions.fieldName)" ... >` is not. It is only selected if you click away from the text. 

In other browsers, clicking in the text selects the tr-ng-sort div.

Could the `ng-click="toggleSorting(columnOptions.fieldName)"` be moved to the tr-ng-title div, so it also works with IE9?

**Comment by MoonStorm** [comment]
This is a bug in IE9 where an absolutely positioned element without a background will ignore the ``click`` event set on it.

Due to how features are being applied by trnggrid, the ``ng-click`` cannot be moved to the parent.

**Comment by MoonStorm** [comment]
Applied some targeted IE styles in 3.0.4. It should be fine now.
