### ISSUE TITLE
keeping table options

### ISSUE THREAD

**Issue by jmls** [MoonStorm/trNgGrid#109]
Hi - been playing with this grid, and loving the simplicity of it all.

Is it possible to use the existing attributes of a table ? For example I have a table with

<div class="table-responsive">
          <table class="table table-condensed table-striped">

and would like to keep the table-striped and condensed options

Alternatively, are there options to get the same effect from trNGrid ?

many thanks

**Comment by MoonStorm** [comment]
Could you please elaborate? What do you mean by "using the existing attributes of a table"?
