### ISSUE TITLE
$sce, Strict Contextual Escaping not possible in custom filter

### ISSUE THREAD

**Issue by howieweiner** [MoonStorm/trNgGrid#111]
Hi

Firstly, great module.. thank you!

I have a filter that returns HTML. However, Strict Contextual Escaping appears to be ignored. See http://jsfiddle.net/howieweiner/fhk93vdr/3/

I've not had a chance to look at the code. Perhaps a display-format-html attribute is also required?

I've got round this issue by writing a TR tag into the table for now.

edit: just noticed this issue that has been rejected https://github.com/MoonStorm/trNgGrid/issues/84

I get your point about filters not outputting HTML. I take your point, though in my experience (as a Django dev) filters are also often used as formatters.

Anyway, what is your suggested approach to formatting cell data? Writing out TR tags will become repetitive in my app. Looking for some re-use

**Comment by MoonStorm** [comment]
Something along these lines maybe? http://stackoverflow.com/questions/28410239/how-to-show-html-content-in-trnggrid-with-sce-trustashtml/28416977#28416977
