### ISSUE TITLE
Dynamically/Pragmatically update Grid's page Size

### ISSUE THREAD

**Issue by naumanasif** [MoonStorm/trNgGrid#114]
Hi, How can I Pragmatically update Grid's page Size? Which property needs to be set.

Consider, data  have been loaded with page size 10. Now I have a dropdown which provide values 25,50,100.  Is there any way when user select 50 then grid's page size becomes 50 and reflect cureent data in grid.

Thanks

**Comment by MoonStorm** [comment]
Thx spacey, that's the one.
