### ISSUE TITLE
Angular 1.3 support

### ISSUE THREAD

**Issue by trahma** [MoonStorm/trNgGrid#115]
It appears trNgGrid will how pagination but will not draw tables when using angular 1.3.  JSFiddle: http://jsfiddle.net/pkuca2f8/58/

**Comment by MoonStorm** [comment]
A quick search around the net for the error revealed this:
http://stackoverflow.com/questions/25679182/angular-1-3-cant-find-the-controller-function

Which means the updated fiddle for angular 1.3 would look like this:
http://jsfiddle.net/MoonStorm/uLhu843v/
