### ISSUE TITLE
Custom cell templates requires a single child element.

### ISSUE THREAD

**Issue by panuhorsmalahti** [MoonStorm/trNgGrid#118]
This is not documented, so it took a while to find the problem.

This doesn't work:
```
 <td field-name='info'>Info</td>
```

This works:
```
 <td field-name='info'><div>Info</div></td>
```

I think this should be either fixed to work without child elements or documented clearly.

**Comment by MoonStorm** [comment]
That's right, sorry for having to find this out the hard way. I've added a sample describing this feature:
http://moonstorm.github.io/trNgGrid/release/index.html#/Customizations
