### ISSUE TITLE
Column filtering based on a list of values

### ISSUE THREAD

**Issue by joejet2222** [MoonStorm/trNgGrid#12]
Excellent, excellent project.

Was trying to see if I could have multiple filters within a column.  Thus, filtering within a column could be within multiple fields.  For example, in a column, if there were A, B, C...you could, filter on A and B which would yield A, B (no C) rather than just A, just B, or just C.  I don't think it was designed to handle this, but would definitely love to hear suggestions as to the possibility.

Many thanks.

**Comment by MoonStorm** [comment]
Here is a bit of inspiration until we get the feature developed. 

http://jsfiddle.net/MoonStorm/8k010nx3/

This one combines the principles of custom formatting and custom column filtering based on a set of values.

**Comment by jdforsythe** [comment]
Perfect. Just what I needed. Thanks again, MoonStorm. I'm working on a large project combining trNgGrid with angular-xeditable. It was tricky at first and there have been a few hiccups. This plunkr solved a major issue. You are the man.

**Comment by edicius6** [comment]
I expanded upon the concept in the plunker example (above) and created a custom directive that extends the TrNgGrid functionality. In case anyone wants to use it I put it on my blog:

**http://www.davidcline.info/2015/08/trnggrid-dropdown-column-filter.html**
