### ISSUE TITLE
Maintaining Grid State (Selected Rows) on Grid that uses Server Side Queries

### ISSUE THREAD

**Issue by mercurydrug** [MoonStorm/trNgGrid#121]
First of all, i am really grateful for this module. It is so awesome, more awesome than any grid module that i found. I can do a workaround in this (create another grid displaying the selected items and not including it in server side queries), but i was just wondering if there is a default implementation of maintaining selected rows when using server side grids.

There is no documentation on how to maintain state of selected rows in a grid that uses server side queries, also the example on server side seems buggy (search filter not filtering correctly, items per page is limited to 5).

Thanks again!

**Comment by MoonStorm** [comment]
You'll have to remember that whatever comes from the server translates into NEW items in the client. So assuming you keep a backup of the previous set of selected items, you'll need to match them with the new items manually (e.g. based on their ``Id`` if you have one) and re-create your selected items. Does it make sense?
