### ISSUE TITLE
Get the page number of specific grid item

### ISSUE THREAD

**Issue by Episodex** [MoonStorm/trNgGrid#122]
Can I get the page number of given item in the grid (respecting sorting, filtering etc)? I can't find any information on this in the docs. I need this for showing right page after performing CRUD operations on grid items (ex. if I change the name starting from A to name starting from Z, I want to switch page to last so the just edited item is visible).
I know how to set the page of the grid, I just need the page number without calculating it manually if possible.

**Comment by MoonStorm** [comment]
I just pushed a new version where you can gain access to the list of displayed items. Knowing that and the page size is enough to compute the page where your item gets displayed, taking the current filtering and sorting into account. The feature was discussed in #139. Check the demo site, ``Grid Options`` section.
