### ISSUE TITLE
Visual Studio required for building

### ISSUE THREAD

**Issue by panuhorsmalahti** [MoonStorm/trNgGrid#127]
I believe the project should include a build script using either gulp (preferred) or grunt. Currently it seems that Visual Studio is required for building.

**Comment by MoonStorm** [comment]
... or just NPM. 

But I'm normally doing all my work in VS, so I never touched any of those. On save, TS gets into JS, JS and CSS get minified, etc. 

But that's just me. Everyone has their own set of tools, and it's easy to attach your own set to this project.
