### ISSUE TITLE
DisplayProperty and ValueProperty 

### ISSUE THREAD

**Issue by furier** [MoonStorm/trNgGrid#130]
I don't see the functionality for having a `display property` which is the one displayed, but the one sorted on or handled otherwise is the `value property`.

This way if I want to sort people by rank where

    var ranks = {
        1: 'Grand Admiral',
        3: 'Commodore',
        5: 'Commander',
        7: 'Lieutenant',
        9: 'Member',
        10: 'Initiate'
    };

    var member = {
        rank: 1,
        rank_display: ranks[1]
    };

    <th value-field="rank" display-field="rank_display" header-text="Rank"></th>

The sorting is done on the numbers instead of the text, which would not be right...

**Comment by MoonStorm** [comment]
With this grid, the original data is meant to remain "untouched". Of course, data can be tweaked to achieve the right form prior to being bound to the grid, but better options come in the form of Angular filters (check this page for details: http://localhost/trNgGrid/release/index.html#/Columns ) or various other means of customizing the cells (details here: http://localhost/trNgGrid/release/index.html#/Customizations )

**Comment by furier** [comment]
I think I may have expressed my self poorly or i'm just stupid and cant see your point...

JS:

	var ranks = {
	    1: 'Grand Admiral',
	    3: 'Commodore',
	    5: 'Commander',
	    7: 'Lieutenant',
	    9: 'Member',
	    10: 'Initiate'
	};

	members.map(function(member){
		member.rank_display = ranks[member.rank];
		return member;
	});

HTML:

	<th field-name="rank_name" display-name="Rank"></th>

OUTPUT:

	---------------------
	| Name	| Rank 	 	|
	---------------------
	| Tyson	| Member 	|
	| Brad	| Commander	|
	| Phys	| Initiate	|
	---------------------

Now if I clicked the `Rank` header to sort members by rank they will be sorted alphabetically and not by actual rank (represented by the `rank` property as a number).

SORT OUTPUT:

	---------------------
	| Name	| Rank 	 	|
	---------------------
	| Brad	| Commander	|
	| Phys	| Initiate	|
	| Tyson	| Member 	|
	---------------------

Initiate is now sorted higher then member...

HTML:

	<th field-name="rank_name" field-value="rank" display-name="Rank"></th>

NEW SORT OUTPUT:

	---------------------
	| Name	| Rank 	 	|
	---------------------
	| Brad	| Commander	|
	| Tyson	| Member 	|
	| Phys	| Initiate	|
	---------------------

Now the sorting algorith will sort on the correct property `rank` but display the `rank_name` property.
This is the prefered outcome.

**Comment by MoonStorm** [comment]
Something like this?

http://jsfiddle.net/MoonStorm/51aj0xL5/

**Comment by furier** [comment]
Just like that!, cool! thanks!
