### ISSUE TITLE
Ability to style a columns content

### ISSUE THREAD

**Issue by furier** [MoonStorm/trNgGrid#131]
Lets say I have a table with positive and negative numbers. 
I don't see the out of the box functionality for colouring the negative numbers red and the positive once green. 

**Is this something you would need to implement or are there any workarounds?**

So far iv been able to colour the cells individually with jquery, but only on the first pagination.
When next page is activated its gone, since the DOM has changed and I haven't been able to hook into any page changed event for the grid to apply the styling again.

**Comment by MoonStorm** [comment]
Templating the data cells will do it:
http://moonstorm.github.io/trNgGrid/release/#/Customizations

**Comment by furier** [comment]
@MoonStorm great work! Thank you! :)

**Comment by randren** [comment]
@MoonStorm Just what I needed.  Thanks!
