### ISSUE TITLE
Expose column ordered, sorted, filtered data for CSV export

### ISSUE THREAD

**Issue by KeithClarke** [MoonStorm/trNgGrid#132]
I've had a couple of customers ask for a CSV export to be added for data presented using trNgGrid. At the moment I just have https://github.com/asafdav/ng-csv exporting the "items" that go into trNgGrid. But it would be better if the column ordering, sorting an filtering applied to the table was respected.

If there is a way (including a hack) for me to obtain that data right now let me know. If not then please consider the provision of CSV export either within trNgGrid itself or in co-operation with other code such as ng-csv in your roadmap.

(I have all the data in the browser - I'm not fetching the data page by page from the server.)

**Comment by MoonStorm** [comment]
You could fork and expose the displayed data via an angular event. Same as in #139.

**Comment by MoonStorm** [comment]
The grid will now report its filtered and paged data. The changes have been pushed to the ``master`` branch.

See the updated [Grid Options](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions) on the demo site for more details.

**Comment by KeithClarke** [comment]
Thanks for addressing this. I'll give it a go the next time I'm working on that code.
