### ISSUE TITLE
Question on display-name

### ISSUE THREAD

**Issue by rex232** [MoonStorm/trNgGrid#133]
does display-name support html style tag? If not, how can i do like as below? thx

<code>
field-name="modifydate" display-name="last modify" 
field-name="modifydate" display-name="<font color='red'>aa</red>" 
</code>

**Comment by MoonStorm** [comment]
``display-name`` is not meant to display HTML. Template the cells in order to apply any kind of decorations:
http://moonstorm.github.io/trNgGrid/release/#/Columns
or:
http://moonstorm.github.io/trNgGrid/release/#/Customizations
