### ISSUE TITLE
creating colunms with ng-repeat fails.

### ISSUE THREAD

**Issue by krikkiteer** [MoonStorm/trNgGrid#134]
Hi there - first of all - awesome grid :-) thanks a lot for this :+1: 

But I'm having an issue.. I'd like to setup the columns for a grid dynamically..
I tried to make that happen by adding

`<th ng-repeat="myfield in grid.fields" field-name="{{myfield.id}}" display-name="{{myfield.title}}"></th>`

and no fields="" -attribute present.
But then, the items don't get rendered anymore.. no errors in console.

If i add the fields=""-attribute to the grid, the column-definitions are being ignored - but i need these in order to specify the display-name ;-)

Is there a way to do what i'm trying ? or is this a bug ?
any help is appreciated! :)

**Comment by MoonStorm** [comment]
Let's call it.... an annoying limitation :laughing: 
 
#91 discusses this.
