### ISSUE TITLE
Computed field does not work as expected

### ISSUE THREAD

**Issue by andrzejpiasecki** [MoonStorm/trNgGrid#135]
I wanted to add a computed field based on documentation:

```javascript
<th field-name="amount" display-format="amountWithCurrency:gridItem">

.filter("amountWithCurrency", ->
    (fieldValueUnused, gridItem) ->
      return gridItem.amount + ' ' + gridItem.currency.code
)
```
but gridItem is always undefined in filter function.

I had to change that to:

```javascript
<th field-name="amount" display-format="amountWithCurrency:filteredItems">

.filter("amountWithCurrency", ->
    (fieldValueUnused, items) ->
      gridItem = items[0].$$_gridItem
      return gridItem.amount + ' ' + gridItem.currency.code
)
```
Grid is not in scope during that piece of code:

```javascript
// apply the format
outputItem[gridColumnDef.displayFieldName] = scope.$eval("gridItem." + fieldName + displayFormat, localEvalVars);
```

**Comment by MoonStorm** [comment]
The documentation site is also a live demo. And it works there.
Could you please isolate the problem in a nice little fiddle? Fork this one if you wish: http://jsfiddle.net/MoonStorm/pkuca2f8/

**Comment by MoonStorm** [comment]
Closed due to inactivity.

**Comment by uNki23** [comment]
i'm facing the same problem. i assume it's because i need to use angular 1.2.9 and trNgGrid 3.0.3 to support IE8. it's working with angular 1.3.1 and trNgGrid 3.1.

http://plnkr.co/edit/95VF9rtkmIoAHOPKEA1T?p=preview

any suggestions how to make this work in 1.2.9 + 3.0.3?
