### ISSUE TITLE
How to make a certain column of table as default sort?

### ISSUE THREAD

**Issue by jithu21** [MoonStorm/trNgGrid#137]
I want to sort the table based on one column of a table while rendering itself how to do that?

**Comment by MoonStorm** [comment]
You can always control the sorting of the grid externally through one of your scoped vars set in the  ``sort-by`` attribute. 

I've changed this page 
http://moonstorm.github.io/trNgGrid/release/index.html#/GlobalOptions
to allow you to manually set the form element associated with the sort column name.

**Comment by MoonStorm** [comment]
A test was also set up for 3.0.4

http://moonstorm.github.io/trNgGrid/release/#/TestItemsUpdate
