### ISSUE TITLE
issue with table border.

### ISSUE THREAD

**Issue by RatanPaul** [MoonStorm/trNgGrid#138]
issue in mozilla browser 34.0.5.
If there is no record in trnggrid then the table border is not visible.
for ex open below link in firefox
and remove the all records from table then you can find the table border is not visible.
for chrome 30+  border is visible (if there is no records in table)
http://moonstorm.github.io/trNgGrid/release/index.html#/Customizations

**Comment by MoonStorm** [comment]
It appears an empty ``TR`` element is required in ``TBODY`` when no data items are being displayed.
http://jsfiddle.net/MoonStorm/oo7oz22d/
