### ISSUE TITLE
Getting the currently displayed elements alone (respecting filtering, pagination and sorting)

### ISSUE THREAD

**Issue by mathanpec** [MoonStorm/trNgGrid#139]
Say when we give 100 objects to the grid and the current page size is 5, Is there any provision to know those 5 objects? Same with filtering also, Is there any way to get the objects which is being displayed as result of filtering or sorting? I couldn't find anything in the documentation.

**Comment by MoonStorm** [comment]
For the time being, no. I believe it could be solved through angular events. Will think about it.

**Comment by mathanpec** [comment]
I have done it using alias in ng-repeat by modifying trNgGrid code (**variable in expression as alias_expression** ). Will raise a pull request for that.

**Comment by jdforsythe** [comment]
@mathanpec can you give more information on how you achieved this? it's a critical feature to my application to export the filtered data to csv and also pass it to another view for a printable report.

**Comment by mathanpec** [comment]
@jdforsythe , In the current version of trNgGrid, currentDisplayItems are being computed as filteredItems. But they aren't just exposed to external scope. So you need to modify the code little bit to get it via external scope same like how you selectedItems is exposed.

**Comment by mathanpec** [comment]
@MoonStorm, I see that filteredItems is being computed internally. But they aren't exposed like selectedItem. Is there any specific reason for not exposing this ? Because I had modified the code little bit to expose this also as isolated scope and wanted to know whether it is right approach?

**Comment by MoonStorm** [comment]
@mathanpec Not a bad solution. The only concern I've got is that being exposed this way it allows for external logic to make changes to the list of displayed items. For the selected items it makes sense to have it that way.

**Comment by MoonStorm** [comment]
@mathanpec  Actually, there is an additional concern. The filtered items you were mentioning are actually already formatted, have the field names mangled, plus they hold a "very well hidden" data item. They were not meant to be exposed. 

The selected items are actual data items.

**Comment by jdforsythe** [comment]
The change I made was

    648d647
    <             scope.$emit('exportableItemsChanged', scope.filteredItems);

It gives me exactly what is in the grid, ordered and filtered, and isn't affected by pagination.

**Comment by MoonStorm** [comment]
Found some time to think about it and decided to implement it via data binding, as @mathanpec  suggested, but instead of exposing the displayed items, it'll provide the data items instead.

Please see the updated [Grid Options](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions) section on the demo site for more details.
