### ISSUE TITLE
Server side pagination & filtering

### ISSUE THREAD

**Issue by k010** [MoonStorm/trNgGrid#140]
First to all thanks for the module is very usefull, now i have a problem with pagination and filtering from server side.
This's the scenario: 
i set a callback function in on-data-required=fn(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse)
First time server-side function return for ex.
- items []
- total-items 100, 
- page-items 10
- etc.
the callback fn set to scope total-items and page-items

The pagination build 10 pages, when click (last or next) fire the funcion and the pagination set in active 2 and legend pagination set: **100 - 100 displayed, 100 in total**. Everything is normaly

But the problem is when i use filter in some field and the server response with other size of element:
- total-items: 20
- page-items 10

The pagination don't reset the legend of pagination needer set the actualy page (currentPage) (still the old)
**100 - 100 displayed, 20 in total** only set the count of total items.

This behavior is only in server-side then pagination and filtering is client-side works fine.
Can you help me ?

Thanks again !

**Comment by MoonStorm** [comment]
Will take a look. Thanks for reporting it.

**Comment by MoonStorm** [comment]
It should be fixed in 3.0.4. The page index will also reset to 0 in most conditions.
http://moonstorm.github.io/trNgGrid/release/#/ServerSide
