### ISSUE TITLE
Support for custom start & stop symbols

### ISSUE THREAD

**Issue by paambaati** [MoonStorm/trNgGrid#141]
`$interpolationProvider` allows us to override the default start and stop symbols from `{{` & `}}` to anything you'd want.

In my case, I use Nunjucks to render some templates, which also uses the same symbols for substitution. Can trNgGrid provide support for custom symbols? ng-grid [just implemented this](https://github.com/angular-ui/ng-grid/issues/1576), but I love trNgGrid too much!

**Comment by MoonStorm** [comment]
Will have a look. Might fit into some other things I have to work on.

**Comment by MoonStorm** [comment]
Released in 3.1.6
