### ISSUE TITLE
Multiple Custom Columns?

### ISSUE THREAD

**Issue by jombee** [MoonStorm/trNgGrid#144]
Is it possible to have more than one custom column? When I put in more than one, the column is rendered but the cells are empty. Is that just how it is presently, or am I doing something wrong?

Here is an example:

```
<body ng-app="myApp">
    <div ng-controller="MainCtrl">
        <table tr-ng-grid='' items='myItems'>
			<thead>
				<tr>
					<th field-name="name" display-name="Name"></th>
					<th field-name="age" display-name="Age"></th>
					<th display-name="Custom Column 1"></th>
					<th display-name="Custom Column 2"></th>
                </tr>
			</thead>
			<tbody>
				<tr>
                    <td>
						<p>test 1</p>
                    </td>
				</tr>
				<tr>
                    <td>
						<p>test 2</p>
                    </td>
				</tr>
			</tbody>
        </table>
</div>
</body>

    function MainCtrl($scope) {
        $scope.myItems = [{name: "Moroni", age: 50},
                 {name: "Tiancum", age: 43},
                 {name: "Jacob", age: 27},
                 {name: "Nephi", age: 29},
                 {name: "Enos", age: 99}];
    };  
```

![1-16-2015 10-41-33 am](https://cloud.githubusercontent.com/assets/8152951/5778859/4cba5072-9d6c-11e4-837c-9b0ccd352bf0.png)

**Comment by MoonStorm** [comment]
This is indeed a bug. Thanks for reporting it.

**Comment by MoonStorm** [comment]
The headers for custom columns should not contain ``display-name`` attributes. I've changed a sample in the ``Customization`` section on the demo site to show how it's done.

**Comment by jombee** [comment]
Very cool, thanks MoonStorm. Love the directive.
