### ISSUE TITLE
$scope.currentPage should return the page number, not the page index

### ISSUE THREAD

**Issue by artganify** [MoonStorm/trNgGrid#146]
As the title states, the value of `$scope.currentPage` should be set to the current page, not it's (array-based) index. When utilizing trNgGrid with pagination using an api today, I got really confused why the value returned on initialization equals **0**, even if the variable is called `currentPage` (and the UI clearly shows **1** as the 'current page'). The section about *Pagination* in the documentation doesn't leave a word about it, only when consolidating the *Server Side Queries* section it became clear that `currentPage` is in fact an index.

Reason:
Queryable apis usually offer an endpoint to fetch data using *?page* and internally calculate the index for skipping on the database. Adding *+1* on the frontend just for an api call which then internally substracts *-1* again for the database query doesn't make much sense. If it is important to return an index instead of the page number, the variable should be renamed to `currentPageIndex`.

**Comment by MoonStorm** [comment]
Yep, I agree, the naming of that attribute and several others could be better. Thanks for the criticism but surely you don't expect me to ruin people's life by changing them overnight :smile:
