### ISSUE TITLE
SingleRow selection doesn't always trigger a change

### ISSUE THREAD

**Issue by vanpouckesven** [MoonStorm/trNgGrid#148]
The documentation states that you can monitor a change in selection in the grid with the following code:
```
$scope.$watch("mySelectedItems.length", function(newLength){
  // your logic goes here
});
```
However this does not seem to be working when switching between an already selected item and a new selection in SingleRow selection without unselecting the current item. 

After a bit of searching I found out that it is better to use $scope.$watchCollection on the entire selectedItems array, rather then watching a change in the length. I tried it on my code and this seems to do the trick. Maybe this information can be added to the documentation? 

See the documentation of Angular for more information on $watchCollection

`https://docs.angularjs.org/api/ng/type/$rootScope.Scope`

**Comment by MoonStorm** [comment]
Yep, that's a bit embarrassing. Docs fixed.

Thanks.
