### ISSUE TITLE
Create child detail row

### ISSUE THREAD

**Issue by dandanknight** [MoonStorm/trNgGrid#149]
Hi, I have a question if I may. Great library by the way.

I'm catching a row click by using the $watchCollection function on the selected rows, and I'd like to write something that will allow me to create child rows which shows additional details when a row is clicked on.

I'm stuck though, as I can't see a way of inserting additional rows into the table that use a custom row template. Can you point me in the right direction please?

**Comment by MoonStorm** [comment]
I'm afraid that's not possible at the moment. It's a planned feature though. #91
