### ISSUE TITLE
Table control layout kind of annoying

### ISSUE THREAD

**Issue by thespiffyitalian** [MoonStorm/trNgGrid#150]
I absolutely love how easy this grid is to implement and how well it works, but the one glaring flaw that I consider it to have is the current layout of the table controls. The biggest problem is the paginator, since as you move through pages the controls move around due to the count displayed text changing. There should also be more pages you could click to other than the one immediately behind and ahead. I also think that an items-per-page control should be available by default, and the global search should be at the top of the table rather than at the bottom.

I personally think that the layout shown here is perfect: http://l-lin.github.io/angular-datatables/#/bootstrapIntegration

I'm working on modifying the template and I may do a pull request at some point, but I did want to bring this up.

**Comment by MoonStorm** [comment]
Even in your example the controls in the pager jump when they reach double digits. 
Point taken though on the count. The order of the count and the paginator can be switched.

I'll think about moving the search on top and having a page count selection available as well (a few other people requested that), but in my mind they should show up as being part of the grid, not floating above the control like in your example.

**Comment by thespiffyitalian** [comment]
Not as much. The main cause of the jump on trNgGrid is from having the total and current item index/count display box to the right of the pager. As the numbers in there change and get larger the paginator starts to move around. You can change the order (which I have in my use of this module), but I really think the display text showing the total and current page index/count should be at the bottom left rather than appended to the paginator.

I'm basically of the opinion that the layout and behavior of the controls in the angular-datatables example is great, or at least more ideal than the current layout. It basically follows the standard set by the jQuery Datatable. It's just that the way your module handles configuration and setup is so clean and easy that I don't want to drop it for something else. So if the table layout can get closer to the jQuery Datatable standard I think that'd be a huge improvement.

**Comment by MoonStorm** [comment]
I understand where you're coming from. Will keep your suggestion in mind for the next major release.
