### ISSUE TITLE
Column Titles not appearing in IE11

### ISSUE THREAD

**Issue by thespiffyitalian** [MoonStorm/trNgGrid#153]
I'm noticing that the column titles are blank in IE11 on the demo and in tables I've implemented for a personal project. 
![blanktitles](https://cloud.githubusercontent.com/assets/2695156/6140647/a7555af8-b14f-11e4-9e92-33f62bebfbde.PNG)

**Comment by MoonStorm** [comment]
I'm never surprised when I hear stuff doesn't work in IE.

Here is the bug report for your issue:
https://connect.microsoft.com/IE/feedback/details/868842/ie-11-setting-css-opacity-on-a-table-row-doesnt-affect-the-background-color-of-that-row

Thanks for reporting this issue. A quick fix is on its way.

**Comment by MoonStorm** [comment]
@thespiffyitalian I just pushed a quick fix in the `release` branch. Could you give it a go and report back please. Thanks.

**Comment by thespiffyitalian** [comment]
Appears to be fixed! Thanks for the quick turnaround =)
