### ISSUE TITLE
How to add index number column?

### ISSUE THREAD

**Issue by chainar** [MoonStorm/trNgGrid#154]
When the ngRepeat is used, it is possible to create a "index number" column as
```javascript
<thead>
                <tr>
                    <th>#</th>
...
<tbody>
                <tr ng-repeat="item in items">
                    <td>{{$index + 1}}</td>
...
```
How can it be done in trNgGrid?

**Comment by MoonStorm** [comment]
Without too much work, you can have the index just for the items displayed on the current page. 
https://jsfiddle.net/MoonStorm/n8pjgh66/
Otherwise, you'll have to provide the numbering either on the items or through other means.

**Comment by MoonStorm** [comment]
Another idea would be to use the reporting capability of the grid and adjust an index property on your entities which is bound to one of the columns. Let me know if you need more help.
