### ISSUE TITLE
custom templates for grid instances

### ISSUE THREAD

**Issue by chachou29** [MoonStorm/trNgGrid#155]
Hello,
I use template cache to define custom global templates. Works fine.
I would like to know if it is possible to define templates for a particular grid instance.
Something like (sorry for the jade syntax):

```
table(tr-ng-grid="XXXX", items="items",  selection-mode="None", fields="fields")

script(type="text/ng-template", id="trNgGridBodyCellTemplate_XXXX.html")
    div(ng-attr-class="tr-ng-cell text-{{columnOptions.displayAlign}}" ng-switch="isCustomized" ng-click="clickUpdate(gridItem)")
        span {{gridDisplayItem[columnOptions.displayFieldName]}}
```

I know that i can define specific rendering for an instance with HTML, but i cannot do that in my case, fields are defined on the server side and get via angular controller/service ...

Thanks

BTW Nice lib ! 
Philippe

**Comment by MoonStorm** [comment]
I'm afraid that's not possible. The templates have an effect on all the instances.

**Comment by MoonStorm** [comment]
I'm thinking that maybe having the option of defining multiple global configurations, which can be referenced by an attribute on the table is the way to go here. Will play around with this idea for the next major release.
