### ISSUE TITLE
Real-World Example of Server-Side Pagination

### ISSUE THREAD

**Issue by nottinhill** [MoonStorm/trNgGrid#156]
I am trying to get Server-Side Queries to work. Unfortunately the Demo Page remains silent about how to  implement this. It mentions only the HTML side of things. But how to exactly request from server it does not say.

E.g. I have a database with 30.000 entries, this is how I request it:

    $scope.docs = DatabaseService.findAll().then(function(response) {
                return response.data;
    });

Now how to combine with:

    $scope.onServerSideItemsRequested = function (currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse) { ... }

I want to request only 1000 items and it should be searchable, e.g. my fields are named:

"Name", "Address", "Gender". How to achieve that if I search for `Name= Alfred` with trnggrid's filter feature, that all 500 "Alfreds" are getting displayed. You get the idea..

**Comment by MoonStorm** [comment]
Same as the ``findAll`` method on your ``DatabaseService``, you can have another one that receives all the parameters from ``onServerSideItemsRequested``. You then prepare a nice request to the server and translate them into a SQL query. The final step is to bring the data down and to set the variables linked to the ``items`` and ``total-items`` attributes.

**Comment by nottinhill** [comment]
Ok; I understand, and it works as you described. However I am not clear about the total items count and its purpose - wouldn't I want to make total items count equal the total number of database entries all the time, in order to be able to page through all items in my database? At the moment I have this value set to 100.000 in order to able to page through all database entries (in a particular data model).

Also I am still still struggeling with filtering when using `onServerSideItemsRequested`, it is not working out of the box.

**Comment by nottinhill** [comment]
I have yet one small problem: When I request let's say all items without a filter and then enter a filter and the results are fetched from my API correctly, it does not get displayed in trNgGrid if the resulting amount is much smaller than the non-filtered amount. As if pagination is not "jumping" to 0 for the new results. I am playing around with `$scope.requestedPageNumber`; but can't get it to work as expected.

**Comment by MoonStorm** [comment]
There was a fix in 3.0.4 regarding something similar to what you're describing:
``The page index now resets in case one of the column filters, the general filter, or the sort column is changed in server-side mode.``
Are you using the latest version?

**Comment by nottinhill** [comment]
Nice! No, not using the latest version - here's a quick fix for old versions:

    function isEmpty(obj) {
          return Object.keys(obj).length === 0;
        }

        if (!isEmpty(filterByFields)) {
            $scope.requestedPageNumber = 0;
        }

whereas you pass ` $scope.requestedPageNumber` to your server / API of course.

**Comment by MoonStorm** [comment]
Placed a link on the demo site pointing to your article.
