### ISSUE TITLE
how can i change the cell font size?

### ISSUE THREAD

**Issue by rex232** [MoonStorm/trNgGrid#157]
I had added font-size in the css but its doesn't work, please help~

.tr-ng-grid > tbody > tr > td > .tr-ng-cell
{
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    font-size:40px;
}

**Comment by MoonStorm** [comment]
It does work:

http://jsfiddle.net/MoonStorm/sk21ckun/
