### ISSUE TITLE
How to get filtering to work with array of items

### ISSUE THREAD

**Issue by vladei** [MoonStorm/trNgGrid#158]
Hi,

I have the following problem . I'm displaying a list of users with all the tags they have with trnggrid. Each user has multiple tags ( tennis, basketball, volley etc) and I display like this: 

```
 <table tr-ng-grid=""
           class="textSelectable"
           items="list.users"
           page-items="50"
           selection-mode="None"
           fields="[ 'tags' ]">
      <thead>
        <tr>
          <th field-name="tags" display-name="Tags"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td field-name="tags" class="tagsCell">
              <div ng-repeat="tag in gridDisplayItem.tags">
                  {{tag.value}}
              </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

```

My problem is that there is no way to filter the table using a specific tag(s). Is there anything that I can do about it? Thank you

**Comment by robertherber** [comment]
This has worked before, but doesn't seem to work in the latest version. We'd very much appreciate a fix for this! :+1:

**Comment by MoonStorm** [comment]
@robertherber I'm not sure it was ever working like that for fields having a value of type array. 
@vladei Support for filtering based on a list of values will come in a future version (see #12). One workaround that comes to mind based on your requirements would be to use computed fields and rely on the grid to perform a dumb search on that virtual field.

http://jsfiddle.net/MoonStorm/zew1djd2/

**Comment by MoonStorm** [comment]
moved discussion to #12
