### ISSUE TITLE
how to use ng-class in tr

### ISSUE THREAD

**Issue by geminiyellow** [MoonStorm/trNgGrid#159]
if i use ngClass in tr, it will be overide by trNgGrid.
e.g. i want to highlight the invalid row.
what can i do?

**Comment by MoonStorm** [comment]
In the current version, you have access to the cells, not the rows. ``tr`` definitions are being ignored. 
The next version will allow for scenarios such as the one you described. 

Please see #92

**Comment by MoonStorm** [comment]
The code for this feature was pushed to the ``master`` branch. There is a sample in the ``Customizations/Per Instance`` section on the demo site.
