### ISSUE TITLE
$compilerProvider enhancement support

### ISSUE THREAD

**Issue by samy100** [MoonStorm/trNgGrid#162]
Any chance why setting $compileProvider.debugInfoEnabled to false fails to render the table in trNgGrid? 
Disabling this enhances AngularJS performance in production environments. See https://docs.angularjs.org/api/ng/provider/$compileProvider for more info.
Note that this would be an enhancement since it only concerns Angular >= 1.3.

**Comment by samy100** [comment]
Note that this would be an enhancement.

**Comment by MoonStorm** [comment]
I just turned this switch off on the demo site and it appears to be working there. Might have been fixed by the recent changes.
