### ISSUE TITLE
How to define properties of Pager

### ISSUE THREAD

**Issue by nottinhill** [MoonStorm/trNgGrid#163]
This is my pager SourceCode:

        <tfoot>
        <tr>
            <td>
                <span tr-ng-grid-global-filter="" ng-model="gridOptions.filterBy"></span>
                <span class="form-group pull-left">
                    <button class="btn btn-primary" style="margin-left: 8px;" ng-click="removeSelectedElements()" ng-class="{'disabled':!isSelected}">Lösche Auswahl</button>
                </span>
                <span tr-ng-grid-pager="" class="form-group pull-left" style="margin-left: 50px; padding-right:15px" cell="0" ng-style="{'width':columnOptions.cellWidth,'height':columnOptions.cellHeight}" colspan="2"></span>
            </td>
        </tr>
    </tfoot>

This is how my pager looks like:

![pager](http://i.imgur.com/WXCDtum.png)

As you can see it is not particularly pretty. There could me more numbers as requested in #150. But more importantly I can't figure out how to control the margins / paddings to the right side. Also it would be neat to make the middle area smaller. Could you help?

**Comment by MoonStorm** [comment]
You won't get ``columnOptions`` inside the footer. Check the final CSS being applied in the browser.

Could you create a fiddle?

**Comment by MoonStorm** [comment]
One last thing before I close this issue down due to inactivity, remember there is a setting to control how many page numbers are shown in the footer. Check the docs, ``pagination``section. Good luck.
