### ISSUE TITLE
currentPage in paging getting reset to 0 even when using ng-model binding to a scope variable

### ISSUE THREAD

**Issue by CarbonFactory** [MoonStorm/trNgGrid#165]
Everything is working fine using the 3.0.4 version. I have a table which uses server-side query and gets displayed properly with paging.

Now, in one of the columns of the table, I have a ui-router link i.e sref attribute clicking on which I navigate to a child state i.e  ` from parent state "view" to child state "view.{number}"`  On each server-side call, I'm caching the search criteria and the page numbers so that I can restore table state.

Now, when I go back to the parent state where the table is defined, in the controller, I'm getting the cached pageNumber and passing it to the server-side query. The server returns correct data as per the pageNumber but the paging starts from 0.

 `<table tr-ng-grid="" current-page="requestedPageNumber" on-data-required="queryServer(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse)" >  </table>`

I can see that the ng-model `requestedPageNumber` becomes 0 after the call to the server has been made. I can explicitly set the model to an integer and it works but it will do one more server call and its not a solution either.

I think the [Issue 28](https://github.com/MoonStorm/trNgGrid/issues/28) describes by issue. But, your [Test Case](https://moonstorm.github.io/trNgGrid/release/#/TestHybridMode) is also failing.

Sorry for not being able to create a plunker for this. If you need more details, let me know.

**Comment by MoonStorm** [comment]
Indeed, the first time around the current page index gets reset to zero, thus blocking you from restoring its state.

**Comment by MoonStorm** [comment]
I just pushed a fix on ``master`` that also fixed the problem on the demo site.
 
Could you please download the grid from there and give it a try. Thanks.

**Comment by CarbonFactory** [comment]
OK. I tried my max to fix this but couldn't. It works fine only when I comment the below line in the code `scope.gridOptions.currentPage = scope.lastPageIndex;` and ironically it does exactly what you have commented above the line as `this will unfortunately trigger another query if in server side data query mode` :smile: 

So, if I don't comment it, it'll fire another GET request to server with the `currentPage` set to 0 making my life hell :expressionless: It would be great if you could fix this.

Also, I did an update via bower and I didn't get the latest src files in to my directory. I had to manually import it. Did I miss something ?

**Comment by MoonStorm** [comment]
Hahaha that's right. That code will trigger another request, but that check is for something else entirely. It caters for situations where you are setting a page index which isn't in the range of pages computed based on the total items count parameter, which in your case **I have a strong suspicion you forgot to set when you restored the state.**

Bower wise, this is still a a Release Candidate. I just want to wait a bit longer till advertising that a new version is out.

**Comment by CarbonFactory** [comment]
OK. I admit I had a constant `2` being set in the callback but even when I set it to the correct count say `10` , its executing another request to server with `currentPage = 0` overwriting correct request. So, I'll keep this bad boy commented out.

So, as of now I got the restore state to work fine  :sunglasses: but only in non-filter mode. With the filter mode set,  its getting a bit complex.

`filter-by-fields="displayTable.filterFields" ` I'm using this to restore the filters on navigating back from child state to parent state. It works but the input is not showing the data in it. 

If the value of the json was like this `"filterFields": { "name": "S" }`, the input associated to the `name` column is blank instead of the having the value `S`. This makes it difficult to clear the filters. I have to input a dummy value and then clear it manually which is a bad bad workaround.

Can you please have a look ?

I'll get you :coffee: if we can get this one addressed :grin:

**Comment by MoonStorm** [comment]
Yeah, it turns out the ``filter-by-fields`` was not monitored for changes coming from the outside. It should be working now. I've also updated the ``Server Side`` section on the demo site with a "live" example, so we can keep an eye on it. Also added it in the ``Configuration`` section. 

The ``total-items`` is a nuisance in server side query mode, and in your case it must be restored as well with the last known value. It doesn't make too much sense I know, as the callback to the server should finally set its value, but for now we'll have to live with it. Otherwise I'll have to put in a bunch of logic to ignore the discrepancy between the restored page index and the number of items, which initially should be ignored. 

And the most important thing to remember, if you do not want to get multiple. make sure you've got the data bound variables set up prior to the grid grabbing a hold of their value.

**Comment by CarbonFactory** [comment]
Thanks a lot. Will get the latest code and test. Good to see the documents being updated as well. You've got a very good library and it should be way more popular that it is currently.  When can we expect the next release ? 22nd March ?

**Comment by MoonStorm** [comment]
Depends on the bugs reported by people till then. And I'm afraid by the looks of things, not well : #167
