### ISSUE TITLE
Problems with Angular Number Filter to round decimals

### ISSUE THREAD

**Issue by nottinhill** [MoonStorm/trNgGrid#166]
I need to round numbers to the 2nd decimal behind the point. I followed http://moonstorm.github.io/trNgGrid/release/#/Customizations_Instance

and tried to implement number rounding like so:

    <tbody>
      <tr>
        <td field-name="street.number">
          <div ng-class="{'text-danger':gridItem.street.number%2}">{{gridDisplayItem.street.number | number:2}} </div>
        </td>            
      </tr>
    </tbody>

However it does not work. Is there an alternate way or am I doing something wrong?

**Comment by MoonStorm** [comment]
The ``gridDisplayItem`` normalizes composite fileld names. So ``street.number`` becomes ``street_number``.

Why don't you use the ``display-format`` attribute on the header cell which is used to apply formatting?

http://jsfiddle.net/MoonStorm/pkuca2f8/203/

**Comment by nottinhill** [comment]
Awesome - works flawlessly!
