### ISSUE TITLE
Angular 1.3.15 breaks 3.1.0 RC

### ISSUE THREAD

**Issue by vedant** [MoonStorm/trNgGrid#167]
There is a change from Angular 1.3.14 to 1.3.15 (released 17 March 2015) that breaks trNgGrid 3.1.0 RC. The expected behavior is that the full grid should render; instead, `<thead>` and `<tfoot>` render, but `<tbody>` does not. All `debugMode` log items register as they should.

See [plunker](http://plnkr.co/edit/uRK4aybUSUNbClgdsXpn?p=preview). If you just change `1.3.15` to `1.3.14`, trNgGrid will render correctly.

**Comment by MoonStorm** [comment]
Thanks for reporting this. I'll have a look asap.

**Comment by vedant** [comment]
Great. Plunker appears to be down at the moment, but to help you replicate, there was nothing special in the Plunker. Totally barebones - a module with a controller, with a `$scope.data` array, and the grid instantiated via `<table tr-ng-grid="" items="data">`.

Thanks for all of your hard work! TrNgGrid is excellent. By far the best we've tested.

**Comment by MoonStorm** [comment]
Yeah indeed something's broke. And it's not obvious where exactly lies the problem. It seems like the watchers aren't working any more. 

This is gonna take a while...

**Comment by strues** [comment]
I'd like to add to the information with this issue. If you start typing into the search box, you will be able to see the data again. For example, typing a space will show everything again.

**Comment by samy100** [comment]
This might be a long shot but it might be due to a fix needed for issue #162. [ChangeLog for 1.3.15](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1315-locality-filtration-2015-03-17) talks about changes in filterFilter which might be worth taking a look at.

**Comment by MoonStorm** [comment]
Changed the ancient binding technique to something a bit more contemporary. Unfortunately that had the side effect of increasing the minimum requirement for Angular to version 1.3.1. Below that version, the default values for some of the grid settings won't "stick". 

Please give it a go and report any problems. Thanks.

**Comment by vedant** [comment]
Works great! Updated the plunker to confirm.

**Comment by xeroxoid** [comment]
I think this also affect version release 3.0.4 with angular 1.3.15.. I just updated and the grid does not render at all.

**Comment by MoonStorm** [comment]
I expected that. The data binding code hadn't changed in a long time.  I'll prepare a new release as soon as the dust has settled over the latest changes. For the poor grid it was like a heart surgery :laughing: :laughing: :laughing: 

It's funny though how you guys update a library as soon as it gets a new version out. I'm curious, was there something in 1.3.15 you desperately needed?

**Comment by vedant** [comment]
No, it's just that in our dev environment we have `bower install` default to the latest supported version.
