### ISSUE TITLE
Access to currently visible items

### ISSUE THREAD

**Issue by i4got10** [MoonStorm/trNgGrid#170]
Hey! It is me again. Followed your example [here](http://moonstorm.github.io/trNgGrid/release/#/Customizations_Instance) and add checkboxes to table. 
But, I cant make it work properly. Problem is that when user click on checkbox in the column header after data was filtered it select all items, but it should probably only select visible items. 

Is there any may to achieve currently visible items?

**Comment by i4got10** [comment]
Sorry, found solution. Did know about `filtered-items-page` attribute.
Probably, you want to update demo example [here](https://github.com/MoonStorm/trNgGrid/blob/gh-pages/demo/js/demo.ts#L140).

**Comment by MoonStorm** [comment]
I was just about to say that. :smile:
