### ISSUE TITLE
How to move Global Search box to header row and add page drop down to footer.

### ISSUE THREAD

**Issue by SuryaPraveenM** [MoonStorm/trNgGrid#171]
Hi ,

I am new to Angularjs and trngrid ,
Please advise me that How to move Global Search box to header row and add page drop down to footer row.

Thanks.

**Comment by MoonStorm** [comment]
You're gonna have to provide your own set of templates. Get some inspiration from the default ones located in ``trNgGrid.ts`` source file.

**Comment by SuryaPraveenM** [comment]
Thanks for response.

I have one more request :

Observed that tbody section is adding after tfooter .
This is causing issue when i open in small devices.

Please advise.

Thanks.

**Comment by MoonStorm** [comment]
The ``tfoot`` section must come before ``tbody``:

http://www.w3schools.com/tags/tag_tfoot.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot

In what mobile browser are you experiencing problems?

**Comment by SuryaPraveenM** [comment]
Hi,

Thanks for your response.

If i open my web page in small screen i am facing pagination issue.

Please find attached image.

Thanks.
![pagingissue](https://cloud.githubusercontent.com/assets/11770420/7006523/7c505288-dc9f-11e4-9c61-de076440369e.PNG)

**Comment by SuryaPraveenM** [comment]
I need to pagination section at the bottom

Thanks.

![pagingissue](https://cloud.githubusercontent.com/assets/11770420/7006541/a1c93d72-dc9f-11e4-860f-c210bb8b3d8b.PNG)

**Comment by MoonStorm** [comment]
The grid relies on the BootStrap CSS for styling its sections. What do you get if you create just a simple plain HTML table in Plunker and apply the BootStrap styles?

**Comment by SuryaPraveenM** [comment]
Hi,

Sorry for late response.

After modifying order of addition in trnggrid.js , i am getting required output.
![trnggrid](https://cloud.githubusercontent.com/assets/11770420/7086434/96d56452-df9e-11e4-9e6a-3d549dc9a366.PNG)


Thanks for your support.

**Comment by SuryaPraveenM** [comment]
Hi ,

One small help,

Can we apply sorting logic to th element for individual columns.
I want sort functionality on click of Column name too.

Thanks.

**Comment by MoonStorm** [comment]
Sorting by clicking on column names should be working.

**Comment by SuryaPraveenM** [comment]
Thanks its working after adding trNgGrid.min.css file.
