### ISSUE TITLE
Default Column Options not Working for Center, maybe others

### ISSUE THREAD

**Issue by samy100** [MoonStorm/trNgGrid#172]
I'm using your plunker here. 
http://plnkr.co/edit/8Plf40gf7aYrYtyu5t82?p=preview
The rows are not center aligned.
Maybe overall it just stopped working on 3.1.0.
It was working before 3.1.0 release.

**Comment by MoonStorm** [comment]
Thanks for reporting this bug samy. The bug was indeed introduced in 3.1.0, when some of the binding mechanisms need to be changes. Sorry about that.

The bug is now fixed.
