### ISSUE TITLE
trNgGrid doesn't resize when the windows changed.

### ISSUE THREAD

**Issue by cemadj** [MoonStorm/trNgGrid#173]
trNgGrid doesn't resize when the windows changed.
I have a trNgGrid, but when i resize the windows , it overlap the windows :-(
Do you have a solution for that?

**Comment by cemadj** [comment]
More explanation: I have large sentences at each ligne. so , when a windows is resized, the ligne doesn't resize!
![bug-eventstatistic](https://cloud.githubusercontent.com/assets/12051493/7271816/64c9b7dc-e8e6-11e4-8d57-8e0e7ebeb758.PNG)

**Comment by MoonStorm** [comment]
You can target the cells with CSS to stop expanding beyond the parent.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by cemadj** [comment]
Hi,
Thanks for the reply.
I try doing it in the CSS file, but it doesn't works
: .tr-ng-grid>tbody>tr>td>.tr-ng-cell{overflow: "hidden";height:
auto;text-overflow: ellipsis ellipsis}

Where can i do it at well.
Periale.

2015-04-24 7:42 GMT+02:00 MoonStorm <notifications@github.com>:

**Comment by MoonStorm** [comment]
Could you please fork [this plunker](http://plnkr.co/edit/WIyzJq?p=preview) and attempt to replicate your issue there.
