### ISSUE TITLE
Pager issue: Pager not updated when column filtering is used

### ISSUE THREAD

**Issue by dasariramacharan** [MoonStorm/trNgGrid#174]
Pager issue: Pager not updated when column filtering is used.

Steps to replicate the issue

1. Goto http://moonstorm.github.io/trNgGrid/release/#/Paging
2. Click on first grid and goto page 3
3. Type 'abcd' in the Id column of the grid
4. you would notice that paging still displays as page 3 

    Expected: to show no results in the pager
    Acutal : shows as page 3

You may notice that this issue does not happen when you use the common search outside the grid instead of column search. 

The issue does not happen to the 2nd grid shown in the same demo page.

**Comment by MoonStorm** [comment]
It does on the second grid as well. It doesn't seem to happen when there are a some items to be displayed as a result of a search. 

Thanks for reporting the issue.
