### ISSUE TITLE
<form> element with bootstrap class="form-horizontal" causes placement issues for Global Search and Paging

### ISSUE THREAD

**Issue by diverkas1** [MoonStorm/trNgGrid#175]
When the grid is located within a <form and the bootstrap class="form-horizontal" is on the form element, the Global Search appears to be pulled left, partially outside the grid control.  The pagination controls are pulled right as well.

**Comment by MoonStorm** [comment]
This seems to be a [Bootstrap bug](http://stackoverflow.com/questions/18429121/inline-form-nested-within-horizontal-form-in-bootstrap-3).
Following the recommendation from that post, adding these to the CSS fixes the problem:
```
         .form-inline .form-group{
            margin-left: 0;
            margin-right: 0;
          }
```
Not sure if it's the right solution though. Here is the [Plunker](http://plnkr.co/edit/8eL6YG?p=preview).
