### ISSUE TITLE
Change currentPage when adding a new item

### ISSUE THREAD

**Issue by untemps** [MoonStorm/trNgGrid#180]
Hi.
Thank you for this great component.
I would like to know if there's an option to change the currentPage index when we add a new item that make the items exceed the page-items value.
To be clear, suppose your page-items value is 3 and you add a fourth item, the grid currently remains on the first page. I need it to switch to the second one.
Is it possible?
Thanks in advance.

Vincent.

**Comment by MoonStorm** [comment]
It should be possible by modifying the scoped var attached to the attribute. When you add the additional item, is the pager reacting to the change in the number of pages?

**Comment by untemps** [comment]
Yes, the pager behaviour is correct.
I bypassed this issue by attaching a var to the current-page value and adding the following code when I add a new item : 

```
var pageCount = Math.ceil(items.length / pageItems);
if(currentPage < pageCount - 1) {
   currentPage = pageCount - 1;
}
```

If it couldn't be the default behaviour, it would be great to have a shorcut for the page count value and some events when the item collection changes.
What do you think?

Vincent.
