### ISSUE TITLE
changing the paging div's position

### ISSUE THREAD

**Issue by hassanwasef** [MoonStorm/trNgGrid#181]
Hello, I am using Trnggrid to view my data.. 
I know that the grid's paging exists in the <tfoot section, How can i move it to the top of the table header. Thank you.

**Comment by MoonStorm** [comment]
Theoretically this can be done by providing your own set of templates to the grid, overriding its defaults. 
As inspiration open the ``trNgGrid.ts`` file on the master branch and have a look at the end of the file. You'll see the definition of the ``TrNgGrid.cellFooterTemplateId`` which contains an element with a ``TrNgGrid.pagerDirectiveAttribute`` attribute. So your override should have that particular element removed and added in ``TrNgGrid.cellHeaderTemplateId``. Problem is you can't put it on its own row in the header so I'm not sure if all this is gonna help you in any way.
