### ISSUE TITLE
Hiding a column from a table with its headers defined

### ISSUE THREAD

**Issue by hassanwasef** [MoonStorm/trNgGrid#184]
Hello, 
I have a question about the way I can hide a column that I use its object to edit the row..in in other words, I want to edit the model depending on an object that exists within a column that i don't want to show, this has forced me to make a header for this column showing it within the table header.. 
what i want is to hide that column without loosing its data while binding its data to the editing modal. 
this is the table design i am working arround: 
            <table tr-ng-grid="" fields="fields" items="items" page-items="myPageItems" total-items="myItemsTotalCount"
                       filter-by="myGlobalFilter" filter-by-fields="myColumnFilter" order-by="myOrderBy"
                       order-by-reverse="myOrderByReversed" current-page="myCurrentPage"
                       on-data-required="onServerSideItemsRequested(myCurrentPage, myPageItems, myGlobalFilter, myColumnFilter, myOrderBy, myOrderByReversed, exportoptionid)"
                       class="table table-responsive table-condensed">

```
                <thead>
                    <tr>
                        <th field-name="name_ar" display-name='@LookupsRes.name_ar' enable-filtering="true" enable-sorting="true" cell-width="10em" display-align="right"></th>
                        <th field-name="name_en" display-name='@LookupsRes.name_en' enable-filtering="true" enable-sorting="true" cell-width="10em" display-align="right"></th>
                        <th field-name="class_value" display-name=@LookupsRes.class_value enable-filtering="true" enable-sorting="true" cell-width="10em" display-align="right"></th>
                        <th field-name="weight" display-name=@LookupsRes.weight enable-filtering="true" enable-sorting="true" cell-width="10em" display-align="right"></th>
                        <th field-name="media_type_name_ar" display-name='@LookupsRes.media_type_name_ar_abs' enable-filtering="true" enable-sorting="true" cell-width="10em" display-align="right"></th>

                        <th field-name="media_type_name_ar_abs">
                            <input type="hidden" ng-model="media_type_name_ar_abs">
                        </th>

                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="hidden" field-name="media_type_name_ar_abs" />
                            <button title="Edit" ng-click="openEditModal(gridItem);" ng-click="openEditModal(gridDisplayItem)" class="btn btn-sm btn-primary">@LookupsRes.edit</button>
                            <button title="Delete" class="btn btn-sm btn-danger" ng-click="deleteItem(gridDisplayItem);">@LookupsRes.delete</button>
                        </td>

                    </tr>

                </tbody>

            </table>
```

I have tried a lot to to hide the th and td but nothing worked. 
I would be grateful to find an option to hide a column . thank you.

**Comment by MoonStorm** [comment]
Controlling the visibility of a column can be achieved via the ``fields`` attribute. Check [this](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions) and [this](http://moonstorm.github.io/trNgGrid/release/#/Columns) for more info.

**Comment by Ahmed-Raouf** [comment]
Hi Moon Storm,
Hope you are fine. 
I have the same issue. I want to pass the gridItem for the selected Item with all columns binded with the gridView. In the same time I want not to show a certain column from the fields list.

If I removed this column from fields list, It will not appear in gridItem object. If I add it to the fields list, it must be displayed in the gridView "I don't want to display it".

I have work-arround to pass this problem:

  <th field-name="id">
                                <input type="hidden" ng-model="id">
                            </th>

But this solution displays an empty column which I want to hide.

Is there any way to achieve this behaviour?

Thanks

**Comment by MoonStorm** [comment]
You're probably binding to ``gridDisplayItem``, which is used by the grid to display the visible formatted columns. You should be working with ``gridItem`` instead, which contains the original data item from the list of items you passed to the grid.

**Comment by Ahmed-Raouf** [comment]
Thanks Moon Storm. I was using gridDisplayItem.
When I used the gridItem, the full object is returned.

**Comment by mod3st** [comment]
There could be an attribute for table head cells (filters, sorting) which prevents creating analogic <filter-name> cells in table body.

**Comment by SebastianBerc** [comment]
+1

**Comment by mod3st** [comment]
Why closed?
