### ISSUE TITLE
Clear column filter programmatically

### ISSUE THREAD

**Issue by nashimus** [MoonStorm/trNgGrid#185]
This isn't so much an issue as a question.  I apologize, couldn't find any other way to contact MoonStorm.  Is it possible to clear column filters programmatically? What is the name of the object in $scope (assuming it's in scope)? E.g. when model that feeds the table is refreshed, it would be nice to also remove any filters.  Remaining filters can confuse users who don't realize that they are restricting what they see, due to the column filter they used.

Thanks,

**Comment by MoonStorm** [comment]
Check [this page out](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions), play with the column filters and watch the value of ``filter-by-fields``.
If you attach your var to that attribute, you can control its value. To clear out the filters you'd have to set it to an empty object.
