### ISSUE TITLE
How to implement a custom global filter input?

### ISSUE THREAD

**Issue by shnar** [MoonStorm/trNgGrid#186]
I'm using the trNgGrid and the requirements I have is to have a Global Filter (like you see at the bottom of the grid when you have enable-filtering set to true), but *not* as part of the grid, and instead in its own <input> element outside of the grid. I cannot for the life of me figure out how to hook up its ng-keypress event to fire the filter on my grid. Are there any examples of how to do this?

-shnar

**Comment by digish777** [comment]
i need this too.

**Comment by MoonStorm** [comment]
What ``ng-keypress``? The first stage is to have your control do what this one is doing here: http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions
Which is as simple as hooking up the ``ng-model`` attribute of the input control to the same scoped variable as the grid's ``filter-by`` attribute. 

The next thing is to either disable the global filtering on the grid, or if that's completely turning filtering off, just hide the particular input control in the footer with targeted css.

**Comment by karthilxg** [comment]
@MoonStorm Hooking up `ng-model` with `filter-by` attribute works perfect !!! 

Now I'm able to hide the global filter from the footer and controlling the search from outside the grid.

I have another question, I would like to use the `global filter` as the `column filter`, in other words I don't want to display the column filter inside the grid I want to move the column filter also outside the grid. Appreciate your help.

**Comment by MoonStorm** [comment]
Bind to your own var and recreate the entire column filter bound to the grid when your var changed:

http://plnkr.co/edit/omp4vJ?p=preview

**Comment by karthilxg** [comment]
@MoonStorm :+1: Thanks!!!
