### ISSUE TITLE
Not compatible with angular 1.4

### ISSUE THREAD

**Issue by imamovic** [MoonStorm/trNgGrid#187]
In bower config as dependency is  ">=1.3". 

But code for checking angular version do not allow to use on Angular 1.4.

```javascript
TrNgGrid.minAngularVersion = { major: 1, minor: 3, dot: 1 };
```

```javascript
if (angular.version.major < TrNgGrid.minAngularVersion.major || angular.version.minor < TrNgGrid.minAngularVersion.minor || angular.version.dot < TrNgGrid.minAngularVersion.dot) {

throw "This version of the Angular library is not supported by trNgGrid.";

}
```

What is reason for checking Angular version it this way or it is error in algorithm. 
Is it supported to work with Angular 1.4. (from my testing I did not find any error with Angular 1.4)

**Comment by MoonStorm** [comment]
Obviously the check is flawed. I was also being a little paranoid a while back when people were downloading the grid without using ``npm`` or ``bower``. Sorry about that.

Thanks for testing it in 1.4 and for reporting this bug.

**Comment by MoonStorm** [comment]
A new version is out with the angular version check removed.
