### ISSUE TITLE
how to refresh the grid after delete

### ISSUE THREAD

**Issue by digish777** [MoonStorm/trNgGrid#188]
Hi,

I have a pop up in the page, once the confirm happens, i am calling service and updating the source list that fills the grid and then redirecting to the page where the grid is. but for some weird reason the grid wont refresh.

**Comment by MoonStorm** [comment]
What do you mean by redirecting to the page with the grid? I would definitely expect a page load to update the grid in that case :laughing: 

In any case, make sure you check with the browser debugger whether the grid is indeed not showing your updated items, in which case try to isolate the issue in a plunker. You can fork [this one](http://plnkr.co/edit/JCLrJD?p=preview) if you want.

**Comment by digish777** [comment]
$scope.Delete = function (id,gridItem) {
        //calling seat alert pop up here
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover record!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        }, function (isConfirm) {
            if (isConfirm) {
            // on confirm i am deleting the user through service           
                var UserDetails = Service.deleteUser(id);  

                 //on confirm i am refilling the data source and reirecting to view
                var UserDetails = Service.getUserDetails();
                promiseUserDetails.then(function (pl) {
                    $scope.UserList = pl.data;

                    //$scope.UserList  UserList is used to fill grid
                     window.location = "#/home/users"; 
                },
               function (errorPl) {
                          $scope.error = 'failure loading User List ', errorPl;
                });      
               swal("Deleted!", "Your record has been deleted.", "success");
               
            } else {
                swal("Cancelled", "Your record is safe :)", "error");
            }
        });

**Comment by digish777** [comment]
in the above code, how to refresh the grid after delete

**Comment by MoonStorm** [comment]
[Here](http://moonstorm.github.io/trNgGrid/release/#/TestItemsUpdate) is a simple test of refreshing the whole data list.

In your case, if this line successfully updates the variable attached to the grid `` $scope.UserList = pl.data;`` in an angular digest cycle, then that's all you need to to. You might need this: ``$scope.$apply(function() {$scope.UserList = pl.data;});``. Also why is this line there ``window.location = "#/home/users"; `` ?

**Comment by digish777** [comment]
window.location = "#/home/users"
redirects to view, that is the intension. hopefully thinking that routing to the same view via:
window.location = "#/home/users"
will update the data source.

**Comment by MoonStorm** [comment]
If you reload you'll lose the updated local data source which means you're loading the data source again from the service?

**Comment by digish777** [comment]
i applied: 
$scope.$apply(function() {$scope.UserList = pl.data;});
and did not do reload. the grid remains unchanged. how about some kind of working sample code. you have time?

**Comment by digish777** [comment]
i am so sorry, it has some mistake with Entity framework deleting system. I traced it. thanks for all the replies back to me.

**Comment by MoonStorm** [comment]
no problem. it happens so many times for me as well.
