### ISSUE TITLE
serverside mode: initialized orderBy, orderByReverse values not used

### ISSUE THREAD

**Issue by dankahle** [MoonStorm/trNgGrid#190]
My on-data-required function works fine when clicking on the sort buttons, i.e. it gets called with the currentPage orderBy/orderByReverse values, but... when I initialize the scope pointing to these values (upon refreshing the page), my currentPage value gets used in the initial call to my on-data-required function, but the orderBy/orderByReverse values don't get sent to the function, even though they do get used to update the grid's sorting arrows.

**Comment by MoonStorm** [comment]
Thanks for reporting this issue. I'll take a look.

**Comment by MoonStorm** [comment]
Couldn't replicate sorry. Could you please fork [this Plunker](http://plnkr.co/edit/WFLMkSLfGLE2TcA8XUpd?p=preview) and help me isolate the problem. Thanks.

**Comment by dankahle** [comment]
My bad, it was a timing issue. I had created a directive to track the query parms and they didn't get done in time for your on-data-required function call. The currentPage value made it, but  orderBy/orderByReverse didn't get there in time. When I moved the code to the controller, it worked as expected. Sorry about that.
