### ISSUE TITLE
Multiple active pager elements when using custom defaultPagerMinifiedPageCountThreshold

### ISSUE THREAD

**Issue by oliver-jonas** [MoonStorm/trNgGrid#191]
When increasing TrNgGrid.defaultPagerMinifiedPageCountThreshold and jumping between pages the clicked &lt;li> elements remain with the 'active' class (selected).

This can be see here: http://i.imgur.com/kjgOJJz.gif

**Comment by MoonStorm** [comment]
Wow. A weird one. Thanks for reporting. I'll take a look.

**Comment by MoonStorm** [comment]
Couldn't replicate. Could you please fork [this Plunker](http://plnkr.co/edit/eFChMB?p=preview) and attempt to showcase the problem for me. Thanks.

**Comment by oliver-jonas** [comment]
Sorry for taking so long to reply. See [here](http://plnkr.co/edit/h6TrQu?p=preview) the a plunker to demonstrate the behaviour.

I think it's related to the dependency on ngAnimate (which we use).

Regards.

**Comment by MoonStorm** [comment]
That appears to be the case. ngAnimate is causing the problem.
