### ISSUE TITLE
how to change the css of trng -grid

### ISSUE THREAD

**Issue by mv2212** [MoonStorm/trNgGrid#193]
Hi,
is there any to customize the css of the trng-grid. to change the look and feel of the trng-grid
ex. bg-color, border etc. if any kindly provide me link if any document for that or any demo links

Thanks

**Comment by MoonStorm** [comment]
[The documentation](http://moonstorm.github.io/trNgGrid/release/#/Customizations_Global) has info on this subject.

The grid is mainly using [Bootstrap CSS](http://getbootstrap.com/). A bunch of [themes](https://bootswatch.com/) for Bootstrap are also available
