### ISSUE TITLE
Paging Threshold Documentation

### ISSUE THREAD

**Issue by Gorkfu** [MoonStorm/trNgGrid#194]
In the paging section of the documentation there's a reference of an option to change the paging threshold. The page states, "You can override the value of the threshold. More information can be found in the Customizations section. " I couldn't find anything in the customizations section regarding this. I would love to see an example of this in action. Thanks.

**Comment by MoonStorm** [comment]
customizations/global:
```
.run(function () {
    TrNgGrid.defaultPagerMinifiedPageCountThreshold = 3;
})
```
