### ISSUE TITLE
Setting Display Name to "" still shows field name on column

### ISSUE THREAD

**Issue by toddhd** [MoonStorm/trNgGrid#200]
http://plnkr.co/edit/BfSOs0?p=preview

I have a column that I don't want to display a column name for (it's just an image of the person and is self-explanatory). Setting display-name="" still shows the field name from the DB. I also tried setting it to " " and even "&nbsp;" but all of the above result in the field name being displayed. 

Is there a way to tell trNgGrid to NOT display a column header? Maybe I'm just going about it wrong.

**Comment by MoonStorm** [comment]
That sounds like a custom column. http://plnkr.co/edit/Bf13hQ?p=preview
You'll get access to your original item with ``gridItem``
