### ISSUE TITLE
Programmatic selection of rows

### ISSUE THREAD

**Issue by HereThereBeMonsters** [MoonStorm/trNgGrid#202]
I am trying to implement simple "select all" / "deselect all" buttons.

I bound the selected items to an array in the scope. I have no problem getting the selected items, from my controller. But adding items to the selection does not reflect on the table, at least not visually.

My selectAll function looks like this :
```javascript
    $scope.selectAll = function(){
        
        var selectedItems = $scope.searchState.selectedItems;
        //empty selection list
        selectedItems.splice(0, selectedItems.length);
        // add all items in the table to the selection list
        angular.forEach($scope.searchState.searchResult.rows, function(row){
            selectedItems.push(row);
        });
        console.log("Selected all");
    }
```

The `$scope.searchState.searchResult.rows` is the same array that is used for the `items` attribute of the table. So at the end of the `selectAll` function, the `selectedItems`array contains all the rows currently in the table.

But no row is highlighted in the table. Even if one or more rows were previously selected, they are not selected any more. So the emptying of the selected items works, but not the adding of new items.

Am I missing something or is this feature not available ? The doc mentions a two-way binding so I was hoping it would work :)

**Comment by MoonStorm** [comment]
Here is a nice game: [wack-a-mole with the selected items in TrNgGrid](http://plnkr.co/edit/JShpL4?p=preview) !!!! 

Isn't it awesome? :laughing:

**Comment by HereThereBeMonsters** [comment]
Awesome game, lol!

Thank you for your reply.

So the selectedItems property 2-ways binding actually works as advertised and it is easy to implement the select all feature : http://plnkr.co/edit/pUqNIvdTeAkL5QAuAkth?p=preview

My problem was coming from the fact that I my table is a search result, and I make it appear dynamically on some user input event. It causes the search request to be called twice, and then then it has trouble recognizing the items. Anyway it is different issue and I might post another issue here with this.

**Comment by MoonStorm** [comment]
I'm glad you got it working. Regarding the data already retrieved from your form, I suppose you can tweak your logic a little bit to make everyone happy. 

Have the callback assigned to the grid with the following logic:

if(gridInitialized){

}
When you request your data via the form, you reset a flag named let's say ``gridInitialized``. You get your data from the server, and the total item count. Enable the grid, and when the gris is firstly asking for data, check the value of the ``gridInitialized`` flag, and if false, you just pass the data and the length you already have and set the flag to true.

**Comment by HereThereBeMonsters** [comment]
Have the callback assigned to the grid check on a flag

Yes, but it's a little more complex isn't it ? When the table actually needs more data, i.e. pagin next/previous page requests, I need to actually reload some data regardless if there already was any before... I suppose I will have to compare the paging parameters to see if they have changed...
