### ISSUE TITLE
Problem with server-side data, paging, and hiding/showing table

### ISSUE THREAD

**Issue by HereThereBeMonsters** [MoonStorm/trNgGrid#203]
The problem is tricky so I hope I can make myself understood :)

So, I have the following situation :

- Table uses server-side data and paging
- The table is initially hidden
- The visibility of the table depends on there being some items to be displayed, i.e. results from a search request
- I want to be able to select items, also programmatically (select all button)

So the flow of execution is the following :

1. User enters some values in a form and clicks on the "search" button
2. This triggers an Ajax search. If the ajax returns some results, they are stored in an object in the $context
3. The number of items it now over zero, so the condition for the table being displayed becomes true
4. The table displays, the `on-data-required`callback is called
5. Problem ! The callback calls the same function that is triggered when the user clicks on the button, that fires and Ajax request. So the request is fired twice.

I could live with that, it still works. But now there is a related problem : since the request is fired twice, for some reason, the items in the table are now not the same as the items stored in my $context variable. I mean the values are the same since the same request was sent, but they are different objects.

So, when I try to add the objects to the selected items, it fails to highlight them.

So, here is a plunker, hopefully better than my confused explanation :) http://plnkr.co/edit/ebRqtY35EcvBPZ65Ea0G?p=preview

I realize that this is an edge case, I don't know if it can be considered a bug. But I would be happy with a workaround that would allow the desired behaviour.

I think the root of the problem is that the onDataRequired is called when the table is displayed, without any paging request from the user. It may be desirable in some cases, but not always. In this case the items are already loaded. Could this maybe be made configurable ?

Sorry for the wall of text !

**Comment by HereThereBeMonsters** [comment]
I got it working by adding a condition in the callback for the table that checks and executes the request only if the paging parameters have changed.

Another problem I faced was that sometimes the data is reloaded, but is the exact same data.

Since it is loaded from Ajax, the array contains objects with the exact same attribute values, but they are different instances of objects so === won't say they are the same.

But since Angular does dirty checking on the actual values, it would not trigger the binding update. So I was once again in a situation where the rows in the table and in my array were different objects and the selection did not work.

I solved that by artificially adding a tomestamp attribute to the objects after I load them from Ajax. It forces Angular to trigger the binding, and the array inside the table is updated.

**Comment by MoonStorm** [comment]
As I answered in the other thread, nothing a good old flag couldn't solve. In addition to that, I replaced the ``ng-show`` with ``ng-if`` so the grid wouldn't ask for data prior to the form search.

http://plnkr.co/edit/vfTDHvbR9NBECNKWeZ3j?p=preview

Of course I might also be missing the point :smile:
