### ISSUE TITLE
Header title alignment

### ISSUE THREAD

**Issue by toddhd** [MoonStorm/trNgGrid#204]
There is an option in the grid to align the data columns using display-align="center|left|right" however this does not apply to the header titles themselves. The column titles are always centered. So for example, if I set the display-align="left", the data will show up left aligned, but the column title will still be centered. 

Is there a flag to set the column title as well, or is just missing? Or centered because that's how the filters are setup?

**Comment by toddhd** [comment]
Just a followup - I see that this is actually set in the trNg-grid css file. At least that means it can be manually set pretty easily. So - up to you if you want to add it as a feature. Seems like it would make sense to have the headers match the data if desired.

**Comment by MoonStorm** [comment]
In the majority of cases, a centered title is preferred. You are free to adjust this via CSS if you so desired.

**Comment by edicius6** [comment]
You can also add this to set globally in the app.run():
`TrNgGrid.defaultColumnOptions.displayAlign = "center";`
