### ISSUE TITLE
onServerSideItemsRequested on Datepicker

### ISSUE THREAD

**Issue by RamonBeast** [MoonStorm/trNgGrid#205]
I've added a bootstrap-datepicker on the header of a trNgGrid, what would be the right way to force a call to onServerSideItemsRequested() so that I can issue a search request with the picked date?

Thank you.

**Comment by MoonStorm** [comment]
I'm thinking [this Plunker](http://plnkr.co/edit/I6JJQD?p=preview) could get you started.
