### ISSUE TITLE
filteredItems not refreshing if data is pulled async

### ISSUE THREAD

**Issue by acwilan** [MoonStorm/trNgGrid#206]
Hi, I have data that is retrieved via $resource and then passed on to a scope variable, that is referenced in "items" attribute of a trnggrid. Then I have another scope variable, let's say "filteredItems" passed on to the filtered-items attribute of the trnggrid. My filteredItems variable (which is initialised to an empty array) is always the same empty array even after the items variable is filled.

**Comment by MoonStorm** [comment]
Sorry for answering late. Is this still an issue for you and could you provide a sample please? thanks.

**Comment by acwilan** [comment]
Kinda. I managed to workaround-it. Used the `on-data-required` attribute and some code in the controller to get the filter done. But not what I expected. I'll se if I can provide a plunkr.

**Comment by PRASAD2344** [comment]
I am also having the same issue, can you please tell the workaround or any way to fix it.

**Comment by MoonStorm** [comment]
What is the difference between your scenario and this live demo: http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions

**Comment by acwilan** [comment]
@PRASAD2344 not the best thing but here's what I did:

Inside the controller:

	angular.module('myModule')
		.controller('UsersCtrl', function ($scope, UserService, myAppConfig, $filter, $rootScope) {
			$scope.totalRecords = 1;
			$scope.filteredEntities = [];
			$scope.pageSize = myAppConfig.pageSize;
			$scope.pageData = {};

			$scope.onServerSideItemsRequested = function(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse) {
				if (!$scope.entities) {
					$scope.busy = true;
					$scope.entities = UserService.query(function() {
						var ents = [];
						angular.forEach($scope.entities, function(entity) {
							ents.push(entity);
						});
						$scope.entities = ents;
						$scope.$watch('search', function(newVal, oldVal) {
							if (newVal !== oldVal) {
								$scope.totalRecords = $filter('filter',$scope.entities,newVal).length;
								$scope.totalPages = parseInt($scope.totalRecords / $scope.pageSize);
								if ($scope.totalRecords % $scope.pageSize > 0) {
									$scope.totalPages++;
								}
								if ($scope.pageNumber > $scope.totalPages) {
									$scope.pageNumber = $scope.totalPages;
								}
							}
						});
						$scope.pageEntities = filterEntities(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse);
						$scope.busy = false;
					});
				} else {
					$scope.pageEntities = filterEntities(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse);
				}
			};
			var filterEntities = function(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse) {
				var entities;
				if (orderBy) {
					entities = $filter('orderBy')($scope.entities, orderBy, orderByReverse);
				} else {
					entities = angular.copy($scope.entities);
				}
				if (filterBy) {
					entities = $filter('filter')(entities, filterBy);
				}
				if (filterByFields) {
					entities = $filter('filter')(entities, filterByFields);
				}
				$scope.pageData = {
					currentPage: currentPage,
					pageItems: pageItems,
					filterBy: filterBy,
					filterByFields: filterByFields,
					orderBy: orderBy,
					orderByReverse: orderByReverse
				};
				$scope.totalItems = entities.length;
				$scope.filteredEntities = angular.copy(entities);
				currentPage = currentPage || 0;
				pageItems = pageItems || 10;
				entities = entities.splice(currentPage * pageItems, pageItems);
				return entities;
			};
		});

In the view:

	<table class="table table-hover table-striped" tr-ng-grid items="pageEntities" total-items="totalItems" page-items="pageSize" on-data-required="onServerSideItemsRequested(currentPage,pageItems,filterBy,filterByFields,orderBy,orderByReverse)">
		<thead>
			<tr>
				<th field-name="username" display-name="username"></th>
				<th field-name="firstNames" display-name="firstNames"></th>
				<th field-name="lastName" display-name="lastNames"></th>
				<th field-name="code" display-name="code"></th>
			</tr>
		</thead>
	</table>

**Comment by acwilan** [comment]
@MoonStorm I think the "items" property was supposed to be pointing to a $ngResource, not a static array

**Comment by PRASAD2344** [comment]
@MoonStorm I am placing plunkr link which defines my scenario.
https://plnkr.co/edit/EqHW3zpicQlsAGFTMhml
