### ISSUE TITLE
Column data not shown if column name has number suffix

### ISSUE THREAD

**Issue by imtiaz-rahi** [MoonStorm/trNgGrid#207]
I have found an issue with column name containing numbers in suffix.
My data structure has multiple columns with names: category1, category2, category3, category4
Data for these columns are not shown in table and table headers all contains identical heading 'Category'.

Please see the plunker at this URL to view this issue.
http://plnkr.co/edit/sBL7Zwfxg3n8YoWCRdoG

The data is available as 'static-data.js'

**Comment by imtiaz-rahi** [comment]
I made a fix of this issue in my own fork.
https://github.com/imtiaz-rahi/trNgGrid/commit/426519ecd35c12fa7e501694e889f2742be60891

**Comment by MoonStorm** [comment]
Thanks. I'll have a look.

**Comment by kenschwartz** [comment]
I just ran into the EXACT issue. Took me hours to figure why it wasn't working (my first time w/trNgGrid). Maybe update the doc?

**Comment by MoonStorm** [comment]
Sorry about that. Will incorporate @imtiaz-rahi 's fix soon.
