### ISSUE TITLE
Additional column with Edit link

### ISSUE THREAD

**Issue by parvanova** [MoonStorm/trNgGrid#208]
Can I have an additional column in which to have a link for editing the current item/row?
Thanks

**Comment by MoonStorm** [comment]
[This thread](https://github.com/MoonStorm/trNgGrid/issues/7) discusses the subject at length.

**Comment by parvanova** [comment]
Thank you for you quick replay. 
In fact I display just a few fields from the item in each row but I want to be able to edit the whole item. That is why instead of using  xeditable I would like to open a modal or a new state of the app to edit the current item with all its fields. So I just need a new column with edit/delete links.
Thanks!
