### ISSUE TITLE
Set display-names as table attribute

### ISSUE THREAD

**Issue by feimosi** [MoonStorm/trNgGrid#210]
Is there a way to declare an array of names I want to display in the table's header? To avoid writing <th> tags for each one. Or the other way: can I force the plugin not to touch field strings: don't upper-case them or anything. That's because this feature is broken - try it with any acronym e.g. MAC.

**Comment by MoonStorm** [comment]
Neither way is possible I'm afraid. You could fork the project and turn off capitalization if you want.

**Comment by feimosi** [comment]
That's a pity. I know I could easily turn it off myself, but I don't want to lose access to future releases for my project. Any chance to see such feature soon? Or what would you say for a PR, just instruct me how to add an additional option.

**Comment by MoonStorm** [comment]
An additional option? For this? No.
