### ISSUE TITLE
Issue when changing the page size via dropdown

### ISSUE THREAD

**Issue by Gorkfu** [MoonStorm/trNgGrid#212]
The issue is that the "1-10 displayed" text doesn't get reported correctly on pages 2+ after changing the page size. For example lets say we have 60 items and on the initial page load paging is set to 5 items. It will display 1-5, then click page 2 it displays 6-10. It works how we expect; However, when we use a dropdown to change the number of items to 10 per page. Page 1 displays 1-10, but page 2 displays 11-60 as the text, when it should display 11-20.

[See this plunker for the issue.](http://plnkr.co/edit/mZhLWF?p=preview)

After making the plunker I see that the page size jumps on page 2 and displays more items than it is suppose to. When I first discovered this I was using sever side queries, so my pages would at least retain the correct number of items.

**Comment by MoonStorm** [comment]
This is a classic angular problem when binding to a select. Your var becomes a string, and is no longer a number. Here's a way of solving this problem:

http://plnkr.co/edit/zNGFCUqoA9W4VHFMYnGk?p=preview

...copy pasted from 
https://docs.angularjs.org/api/ng/directive/select
