### ISSUE TITLE
Loading es5-shim causing issues in Pager - PageIndex repeating multiple times

### ISSUE THREAD

**Issue by karthilxg** [MoonStorm/trNgGrid#214]
@MoonStorm Loading `es5-shim.js` causing issues in the pager, the page numbers are repeating multiple times. This issue occurs only in `Safari` browser `Version 8.0.8 (10600.8.9)`.

> Note: Loading es5-shim version < 3.4.0 works fine. 

*Plunker* http://plnkr.co/edit/NLmPRLsyYv5NMT33digC?p=preview

![image](https://cloud.githubusercontent.com/assets/3691228/10522185/b8f7f7ca-7328-11e5-82ec-469a6f10334a.png)

**Comment by karthilxg** [comment]
It looks like the `es5-shim` has issue with the `splice` function implementation.

At line [1123](https://github.com/MoonStorm/trNgGrid/blob/master/trNgGrid.js#L1123]) pageIndexes array is getting cleared but es5-shim splice is not clearing the array.

```js
scope.pageIndexes.splice(0);
```

**Comment by iamvenkat45** [comment]
+1

**Comment by karthilxg** [comment]
The problem is with `es5-shim` `splice` prototype implementation https://github.com/es-shims/es5-shim/issues/328.

**Comment by ljharb** [comment]
See https://github.com/es-shims/es5-shim/issues/328#issuecomment-148560011 - this is actually a change in ES6 that breaks compatibility with ES5.

`es5-shim`'s splice implementation conforms to ES5, not ES6 - if you file an issue on `es6-shim`, I'll make it correct any ES5-conforming implementations.

My recommendation would be to never use `splice` anyways - if you want to clear an array, set `length` to `0` - and if you want to keep the contents, `slice()` it first.
