### ISSUE TITLE
data-i18n in <th> element suppresses sorting and filtering 

### ISSUE THREAD

**Issue by avanttech** [MoonStorm/trNgGrid#216]
Whenever the following table definition is used with the data-i18n entries, filtering and sorting is suppressed and trNgGrid is not rendering filtering text box and sorting arrow under each column. Somehow the angular translation using i18n interferes with tr-ng-grid's display.
```
  <table tr-ng-grid="" page-items="perPageGrid" items="data"  selection-mode="SingleRow"  >
	<thead>
	<tr>
	  <th field-name="state" enable-sorting="true" data-i18n="state"></th>
	  <th field-name="couponCode" enable-sorting="true" data-i18n="coupon code"></th>
	  <th field-name="name" enable-sorting="true" data-i18n=name"></th>
	  <th field-name="store" enable-sorting="true" data-i18n="store" ></th>
	  <th field-name="redeemDate" enable-sorting="true" data-i18n="redeem date" display-format="dd MMM yyyy"></th>
	</tr>
	</thead>
  </table>
```

**Comment by MoonStorm** [comment]
Many directives on the table's elements are not supported.
The first page on the demo page lists the current limitations of the grid.

**Comment by avanttech** [comment]
It'd be pretty tough to implement localization in the grid then. Please let me know if there are any alternatives?
