### ISSUE TITLE
How to integrate bootstrap pagination and replace the trNgGrid pagination?

### ISSUE THREAD

**Issue by Sandeep546** [MoonStorm/trNgGrid#217]
Hello,
Can you please provide a sample or provide some info to integrate bootstrap pagination and replace trNgGrid pagination

**Comment by MoonStorm** [comment]
The [customization section on the demo site](http://moonstorm.github.io/trNgGrid/release/#/Customizations_Global) gives you an example of how to change the default template. The original template can be found in the js/ts file. Search for TrNgGrid.footerPagerTemplateId.

**Comment by Sandeep546** [comment]
Cool thanks...
