### ISSUE TITLE
Use both: filter & custom template in body

### ISSUE THREAD

**Issue by phucdat1d** [MoonStorm/trNgGrid#218]
...
```html
<th enable-filtering="true"></th>
```
...
```html
<td><button>gridItem.name</button></td>
```
....

if I define field-name in < th > tag, custom template in body is lost.
If not, filter box of all columns as same model and filter-by-fields only return one value.

Could you help my case.

**Comment by MoonStorm** [comment]
I believe there are plenty of examples in the docs to help you with this.

**Comment by phucdat1d** [comment]
Thanks for your feedback,

I still cannot find any help from docs. Could you check my sample at http://plnkr.co/edit/SLPruZTuepIwCw0wKJoY?p=preview
My issue: I cannot make filter button name => because three filter boxes are same model.
Thanks again.

**Comment by MoonStorm** [comment]
I'm not entirely sure I understand. The idea is to match the THs with the TDs. Also make sure there is a single HTML element inside of them, such as a DIV. Under the DIV it can be anything, the library doesn't care.

http://plnkr.co/edit/iKZUuLK9VFsIUZbLyK25?p=preview

**Comment by phucdat1d** [comment]
That's extract what we need. Thanks so much.
