### ISSUE TITLE
cannot apply order-by for property without column

### ISSUE THREAD

**Issue by etaiso** [MoonStorm/trNgGrid#219]
In my JSON I return a few properties, for e.g: {id, name, date}.
I want the table to show only 'name' and 'date', but sort it by the 'id', 
If I don't display the 'id' column then the order-by is not working.

example:
```
<table tr-ng-grid="" items="myItems" selected-items="mySelectedItems" orderBy="id" page-items="5">
    <thead>
        <tr>
            <th field-name="name"></th>
            <th field-name="date"></th>
        </tr>
    </thead>
```

In this case the items will not be orderd by id, as id is not presented in <thead>.

Is there another way to do this or this is not supported or rather an issue?

**Comment by MoonStorm** [comment]
As there is no column dedicated to the ``id`` field, the grid is going to ignore it as well. I suggest passing to the grid a list of items already sorted by id. This can be done either server side or client side by your code in js, prior to it being passed to the grid.
