### ISSUE TITLE
Fixed header and footer

### ISSUE THREAD

**Issue by jonagoldman** [MoonStorm/trNgGrid#22]
Hi, is there way to make fixed headers and footers?

Like in ng-grid:

![image](https://cloud.githubusercontent.com/assets/1297559/3351596/a6eade0a-fa14-11e3-9242-455f35f53fb4.png)

Thanks!

**Comment by solidevolution** [comment]
Can you give me a perspective, if or when you will re-visit this feature/enhancement.
Currently we use you're grid with server side request, sorting, filtering and paging. We tweaked a lot on style but I don't want to do this tweak, too. If there is no plan for fixed header/footer on your side, we will build the grid without table html self, with angular or react.

**Comment by MoonStorm** [comment]
Sorry I don't plan on revisiting this feature.

**Comment by solidevolution** [comment]
Allright, thanks for the fast response and this good module. 
It helped me a lot while starting with angular / SPA.
