### ISSUE TITLE
Global Search tilter text set bold

### ISSUE THREAD

**Issue by Sandeep546** [MoonStorm/trNgGrid#220]
Hello,
I am trying set the match text from global search filter to bold/highlight in yellow color. And I would like to achieve this with out changing the trNgGrid.js code. Can you please suggest if I can add this with a wrapper directive/ filter on top of trNgGrid directive.
Thanks 
- Sandeep.

**Comment by MoonStorm** [comment]
You could try to override the default templates. The docs have more info on this. The effort though isn't worth it, at least in my mind.
