### ISSUE TITLE
can you please make your grid responsive.

### ISSUE THREAD

**Issue by digish777** [MoonStorm/trNgGrid#221]
can you please make your grid responsive. This is a kind of feature request.

**Comment by MoonStorm** [comment]
A sample of the problem would have been nice. Most likely I wouldn't have a solution anyway but still...

To give you a broad answer, if you were after speed then you've picked the wrong technology from the start. Angular is notoriously slow compared to a pure JS solution. That is because of all the dirty checks it performs on the scoped vars.

**Comment by digish777** [comment]
i develop applications based on angular. as of now, i am not that serious about speed of angular, as it is million times better than asp.net mvc and forms or a java based site.

now, about pure js, pure js controlling is tougher, and making it happen in good application takes time. Enterprise wont wait for answers, they want product ready.


coming to responsiveness, why i requested. I love the grid you made. the only ready, i cannot bring your grid to my applications, is due to responsiveness. it simple wont work in mobile screen, if it were div based, with flex model and supports ie9+, then I would have been able to bring your grid to my applications. I even thought of forking. I might even end up doing that.but my first thought was ask.

**Comment by MoonStorm** [comment]
``trNgGrid`` and ``Smart Table`` are table based grids. They started because we didn't like the DIV spaghetti nor the poor performance that comes with it. You are free to fork the grid and create a DIV based one. I will never go back to divs for rendering this kind of data sorry.

**Comment by ThisNameNotUsed** [comment]
If you make your column names multiple words long (ie "number of instances" instead of "instances") the grid will expand the window size up to the maximum width needed to display all the words in a single row and contract to put all the words in their own row. It's kludgey as heck but it works.
