### ISSUE TITLE
Trying to add dragtable for reorder

### ISSUE THREAD

**Issue by spandana197** [MoonStorm/trNgGrid#223]
Hi,

I am trying to add this plugin on top of the trng grid for it to have drag and drop ability. It all works well but as soon as I enable sorting, the content td's are not working as intended and are sorting going back to their original position

**Comment by MoonStorm** [comment]
If your solution is manipulating the HTML, this will never work. Angular is a data driven HTML template framework. The moment it detects changes in its data input, it will recreate the HTML. What I'd suggest you try is to assign a scoped variable to the ``fields`` attribute and change it in an Angular context when the column dragging has finished.
