### ISSUE TITLE
not sorting on custom objects

### ISSUE THREAD

**Issue by robrotheram** [MoonStorm/trNgGrid#226]
My problem is that I need to be able to change a individual cell background to a differnet color for example a status column where if there was a error it would highlight the cell. I was able to do this by making the data a custom object ie {value:"OFF", cssclass:''} and then I was able to set the cssclass and get the table cell to change color in the table I have this code that will output the value and allow angular to change the css class

      <td field-name="name"ng-class="gridDisplayItem.name.sclass"><div>{{gridDisplayItem.name.value}}</div></td>

My problem is that now I can not sort or filter the columns. any idea of either how to get the search and sort to look at the object value field or a way that sill allows for cell background changes that allow searching.

This is one excellent lib I would hate to have to find a new one

**Comment by MoonStorm** [comment]
While I could say it's a bad idea to mix up data with presentation like that, at the same time I always hated people avoiding giving an answer to the question.

Try to set the ``field-name`` to be ``name.value`` in your case. Get access to your original item with ``gridItem``, versus ``gridDisplayItem``, which only gives you the formatted displayed values.

**Comment by robrotheram** [comment]
Hi thanks for getting back to me, setting the feild-name to name.value did not work, but on a happy note I worked out an alternative that works for me. 

I reverted back to not using any custom objects to store cell data but added a small function in the ng-class that takes the cell value and if it matches returns the css style to use. The html for the new row structure 

    <td field-name="status" ng-class="valueToCss(gridItem.status)">{{gridItem.status}}</td>
    //function in the controller
    $scope.valueToCss =function(id){
    	if(id=="true"){
    		return "cell_yellow"
    	}else{
    		return "cell_green"
    	}
    } 
you have to do this for every column that you want conditional formatting on which is not ideal but it works well enough for me hope the code snippet helps anyone else who needs a form of conditional formatting.
