### ISSUE TITLE
require can't find module

### ISSUE THREAD

**Issue by Katuva** [MoonStorm/trNgGrid#228]
I'm using browserify to transpile my js, and everything else works perfectly.

I installed trNgGrid via npm, and its been added to my node_modules, I then try and require it, but when I run gulp, it can't find the module.

```
require('angular');
require('angular-ui-router');
require('tr-ng-grid');
```
`[01:02:08] gulp-notify: [Laravel Elixir] Browserify Failed!: Cannot find module 'tr-ng-grid' from`

Its the only module I've come across that is giving me issues.

**Comment by Katuva** [comment]
I had to do the following:

`require('../../../node_modules/tr-ng-grid/trNgGrid.js');`

No idea why, when every other module I use is resolved correctly, including others I require further down.

**Comment by scottadamsmith** [comment]
the package config is missing the main attribute, so it does not know to look for trNgGrid.js. I think that is all that is needed to fix this.

**Comment by Katuva** [comment]
That's awesome, thanks for that :+1:
