### ISSUE TITLE
Please Make API Documentation

### ISSUE THREAD

**Issue by engemasa** [MoonStorm/trNgGrid#230]
Please make an API document for this. It would be Extremely helpful!

**Comment by MoonStorm** [comment]
You mean for the JS stuff? Because ``trNgGrid`` really does all its work via HTML attributes.

**Comment by engemasa** [comment]
Well, it would be handy to see every setting/config available. I feel there
is more available than the current "doc" page is showing.

On Thu, May 5, 2016, 4:41 PM MoonStorm <notifications@github.com> wrote:

> You mean for the JS stuff? Because trNgGrid really does all its work via
> HTML attributes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MoonStorm/trNgGrid/issues/230#issuecomment-217271995>
>
-- 
Scott Engemann
www.scottswebs.net
