### ISSUE TITLE
one way data binding

### ISSUE THREAD

**Issue by ehsaanwelcome** [MoonStorm/trNgGrid#233]
it will be great to consider one way data binding in fields array

i can do it by overriding tbody but then fields array will be useless because i have to prefix :: every td

this thing will also improve speed of grid by many folds

**Comment by MoonStorm** [comment]
The fields array is data bound. Check out the [demo page](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions). Uncheck the autodetect on that page.
