### ISSUE TITLE
trNgTable select fields from JSON Array

### ISSUE THREAD

**Issue by PrabhakarVijendar** [MoonStorm/trNgGrid#238]
this is my JSON data

  {
        "id": 1, 
        "project_name": "Temp Project", 
        "project_startdate": "2016-04-28T12:08:45Z", 
        "created_at": "2016-04-28T12:08:45Z", 
        "updated_at": "2016-04-28T12:08:45Z", 
        "project_status": "Initial", 
        "customer": {
            "id": 1, 
            "cust_firstname": "James", 
            "cust_lastname": "Paul", 
            "cust_company": "test", 
            "created_at": "2016-04-28T12:05:22Z", 
            "updated_at": "2016-04-28T12:05:22Z", 
            "cust_contact_number": 234432, 
            "cust_email": "james@test.co.uk", 
            "cust_address": "United Kingdom"
        }, 
        "employee": {
            "id": 1, 
            "employee_firstname": "kiran", 
            "employee_lastname": "kumar", 
            "created_at": "2016-04-28T12:02:28Z", 
            "updated_at": "2016-04-28T12:02:28Z", 
            "employee_contact_number": 998046, 
            "employee_email": "kk@gmail.com", 
            "employee_designation": "Project Manager", 
            "employee_address": "Bangalore"
        }
    }, 

i want to display Employee name and Customer Name in the table column. How can i do that

**Comment by MoonStorm** [comment]
Check the ``computed fields`` section under the ``columns`` topic in the docs.
