### ISSUE TITLE
package.json.main issues.

### ISSUE THREAD

**Issue by aluanhaddad** [MoonStorm/trNgGrid#239]
Do to the recent inclusion of the `"main"` property in package.json, suggests that the library has an export. This causes issues because the variable `TrNgGrid` is only registered as a global if the module itself is not wrapped in an IIFE. However, the presence of  `"main"` suggest suggests that it is self contained and can be wrapped.

This causes difficulties for certain module loading scenarios, resulting in a `TrNgGrid` is undefined error when attempting to set properties for configuration.

Perhaps it would be best to commit to the global nature of the library by explicitly setting

``` typescript
window.TrNgGrid = TrNgGrid;
```

**Comment by MoonStorm** [comment]
That workaround looks fine to me. The TS compiler can also output JS compatible with a provided module system. I'll try to find some time to have a look at all the different options.

**Comment by aluanhaddad** [comment]
Thanks for looking into this. I actually write most of my client side code in TypeScript and I'm familiar with targeting the various module formats it supports so let me know if there's anything I can do to help.
