### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by ehsaanwelcome** [MoonStorm/trNgGrid#242]
Hi,
I did tried many libraries such as ngTable and UiGrid but really liked this one and now totally dependent on this one.
We have a plan to migrate to Angular 2 as release candidate is out.
Do you have a plan to rewrite this for Angular 2?

**Comment by MoonStorm** [comment]
It's too early to tell but I'm sure somebody is gonna find time to rewrite it for Angular 2. Potentially that would also give us the chance of getting rid of some of its limitations. 

I just made the project npm/gulp friendly with support for ``browserify``, so hopefully this would appeal to an even greater audience.

**Comment by caboosesw** [comment]
Just wondering what limitations you refer to ... what are your greatest concerns?

**Comment by MoonStorm** [comment]
The ones described here: http://moonstorm.github.io/trNgGrid/
