### ISSUE TITLE
Can we have "Go to Page" drop down for setting the current-page in the grid?

### ISSUE THREAD

**Issue by sumeshk** [MoonStorm/trNgGrid#244]
Hi,

I agree with others that this is an amazing grid. I would like to have this additional feature where you can select a page manually without going through the next button. 

In my scenario, I am using server side pagination and there are around 30 pages. If I want to select a page somewhere in between, I have to navigate using next button and since each button click does wait for the server to return the data for the corresponding page, its a time consuming process. 

Increasing the page count is not a desired option all the time. I prefer to have a drop down where I have the flexibility to select the page number and go to it directly. I tried this using a drop down outside the grid and it kind of works with some minor issues(not in logic but suddenly lot of page numbers gets visible to select in the pagination panel of tr-ng-grid).

It would be great if this feature can be added to the grid.

Thanks,
Sumesh

**Comment by MoonStorm** [comment]
Its hard to satisfy everyone's needs, reason why its section templates have been exposed in order to make them easy to customize. [Here's a section in the docs](http://moonstorm.github.io/trNgGrid/release/#/Customizations_Global) that shows how to customize  the pager.
