### ISSUE TITLE
No server side refresh with custom filters outside the table / fields

### ISSUE THREAD

**Issue by solidevolution** [MoonStorm/trNgGrid#245]
Hello MoonStorm,

first, thanks for this Package, it was very helpful to create a server side grid with page, sort, filter and multi-select functions.

Currently, we are unhappy with the filters (ByFields) on every table column. (it's a design crasher for us)

So I tried to build own filters in an own filter bar on top of the table which manipulate the grid variable in "filter-by-fields". (i've also tried "filter-by") 

I created an simple input with ng-model, interacting but the grid don't refresh the server side. It only works after filtering in column. I tried then to update the currentPage filter to 0 but this also didn't work. Why doesn't react the watcher on GridOptions.filterByFields? I don't want to call the method inside "on-data-required" manually because then I have to pass it all 6 parameters again manually.

Here the head definition html code:

```
<table class="table table-hover table-striped"
                tr-ng-grid=""
                locale="{{$root.translateService.use()}}"
                items="vm.itemService.items"
                current-page="vm.itemService.pageCurrent"
                page-items="vm.itemService.pageItems"
                total-items="vm.itemService.totals"
                filter-by-fields="vm.itemService.filter"
                on-data-required="vm.itemService.request(currentPage, pageItems, filterBy, filterByFields, orderBy, orderByReverse)"
                selected-items="vm.itemService.selected"
                selection-mode="MultiRowWithKeyModifiers">
...
```

**Comment by MoonStorm** [comment]
Try to make it work in regular mode first. This demo page http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions is actually using what you described. The global filter on the left hand side is bound to the same scoped variable as the one attached to the grid.
