### ISSUE TITLE
Apply custom attributes to each datacell

### ISSUE THREAD

**Issue by Figedi** [MoonStorm/trNgGrid#246]
So I'm kinda helpless right now. I need to apply custom attributes to each data-cell in tbody. The thing is that this depends on the col's data-value. As far as customization goes, my understanding was that I could only access the current gridItem (which is the row), but not the current datacell (the col). Manipulating on col-level requires the field-name, which I cannot dynamically access from the gridItem.

My current approach  is that I've made a directive, which parses the thead Element and then injects the respective <td> tags in a <tr> row in <tbody>. However this shows very poor performance. Is there any other way to define data-attributes for each td in a row?

Cheers,

**Comment by MoonStorm** [comment]
You will know the name if you know the fields of the data that is going to get attached to the grid.
Like in one of these examples: http://moonstorm.github.io/trNgGrid/release/#/Customizations_Instance

**Comment by Figedi** [comment]
yes this is true, but this is cumbersome for sets with a lot of columns + its not dynamic. say I want to add a translation data attribute. The key resides in the provided data (i.e. column data). Automatically inserting this would be possible if one could access the current column and not only the current row
