### ISSUE TITLE
Using a select element when row is selected

### ISSUE THREAD

**Issue by engemasa** [MoonStorm/trNgGrid#247]
I'm trying to display a select box in a column of a row only when said row is selected. However, when trying to change the select element it's disappearing immedately. I believe it's a "bubbling" issue.

Here's the plunker with the error: http://plnkr.co/edit/6rcFjVlBBJKfZtskbRXQ?p=preview

Select a row then try to change the option in the select box with the mouse. You can't. Same is true if you it was an input element.

**Comment by MoonStorm** [comment]
I guess you're gonna have to stop the propagation of the click event to the parent:
http://stackoverflow.com/a/1369066/954407

**Comment by engemasa** [comment]
Looks like that will work.

To be clear for anyone else that comes across this, add the following to the element that you are clicking on in the row

`ng-click="$event.stopPropagation()"`

For my case I put this on the select element.
Updated Plunkr: http://plnkr.co/edit/6rcFjVlBBJKfZtskbRXQ?p=preview
