### ISSUE TITLE
Any idea on how to implement the grid with paging by calling data page per page 

### ISSUE THREAD

**Issue by metalmannight** [MoonStorm/trNgGrid#249]
Hi,

First of all, great job with this tr-ng-grid, I love it.
Do you have any idea how to implement the paging while making calls page by page?
I ask because we've had timeouts before when loading 8000+ items (rows) of limited data, and can't expand response time/size.
Is there a way to set the number of pages and the number of items as parameters, and link the sort (if possible even filter) with servicecalls/functions?

It would be of great help.

**Comment by metalmannight** [comment]
Ok, sorry, I found all the information [on this page](http://moonstorm.github.io/trNgGrid/release/#/ServerSide) ... thank you again for the great work!

**Comment by MoonStorm** [comment]
I was just about to make you aware of that part of the docs. Glad you found it.
