### ISSUE TITLE
Get new list after filter into model

### ISSUE THREAD

**Issue by mathben** [MoonStorm/trNgGrid#252]
Hi, is it possible to get the new list of items after we update filter?

I would like to export table into csv file and let user select with filter information needed.
(the filter is in column header)

Thanks!

**Comment by mathben** [comment]
A solution can be to select all after filter. How can we do this?

**Comment by MoonStorm** [comment]
You can access them by attaching to the [grid's reporting vars](http://moonstorm.github.io/trNgGrid/release/#/GlobalOptions).

**Comment by mathben** [comment]
Thank you!
