### ISSUE TITLE
unable to view documentation

### ISSUE THREAD

**Issue by juggernaut451** [MoonStorm/trNgGrid#254]
it is giving 404 on opening http://moonstorm.github.io/trNgGrid/release

**Comment by JonnyDotNet** [comment]
Me too

**Comment by EssyTech** [comment]
Yep it is broken here as well.

**Comment by MoonStorm** [comment]
It was a glitch on the GitHub's side. Seems like touching the ``gh-pages`` branch fixed it.  Should be all good now.
