### ISSUE TITLE
How to dynamically add and remove columns

### ISSUE THREAD

**Issue by tedjt** [MoonStorm/trNgGrid#4]
I was wondering the best approach to be able to dynamically add or remove columns. I have data objects with many more fields than I want to display and I want to let the user select the columns they want.

Right now all the column properties are defined on the TH elements in the table head. It would be nice to be able to define them on a watched object in the parent controller scope. I'm not an angular expert and would appreciate any pointers.

**Comment by dasilvas3** [comment]
Can you share that with us malplayer. thanks
