### ISSUE TITLE
HTML in grid column cells

### ISSUE THREAD

**Issue by imrepnw** [MoonStorm/trNgGrid#47]
I'd like to put an HTML link tag into column cells. I tried to use a custom column, but then I can't sort or filter. I also tried a normal column using display-format attribute with a custom Angular filter, but in this case Angular converts the tag into text, e.g. it replaces < with &gt; and < with &lt;. Based on my research I would need to use ng-bind-html-unsafe attribute for the <td> elements to be able display the HTML properly. Is there anything I can do to make this work ?

**Comment by randren** [comment]
This is it!

**Comment by merenzo** [comment]
For me, this only worked when I wrapped my custom cell format in a `<div>` tag, e.g. [Plunker](http://plnkr.co/edit/GTRCQ40FsM2imLx9QCHy?p=preview)

**Comment by jombee** [comment]
For me, it only works with the div as merenzo said, and then only on the first column.

**Comment by MrBliz** [comment]
` <td field-name="name">
                    <div>
                        <a  ui-sref="event.details({eventId : gridItem.id})">{{gridItem.name}}</a>
                    </div>
                </td>`

Can confirm that it only appears to work when you wrap the link in a div. 

But i can get it to work on any column, not just the first.
