### ISSUE TITLE
How can I highligth row by field 

### ISSUE THREAD

**Issue by oblin** [MoonStorm/trNgGrid#48]
Look to examples but didn't find out the solution.
If I want to highlight a row by its field value (for example: item.Id = 1) with certain class, look like:
<tr ng-class="item.Id == current.Id ? 'active' : null">

How to implement?
Thanks for help.

**Comment by MoonStorm** [comment]
The code for this feature was pushed to the ``master`` branch. There is a sample in the ``Customizations/Per Instance`` section on the demo site.
