### ISSUE TITLE
HTML5 data-* are not supported

### ISSUE THREAD

**Issue by yilativ** [MoonStorm/trNgGrid#51]
Here's a plunker that should work as it is just a minimum setup defining columns inside thead, but as you will note, the "I'm never shown" is indeed never shown, and the last field in the array is used instead: 

http://plnkr.co/edit/UwB2pVTqhKi9Im9SY0nz?p=preview

When setting the data-fields=[...] attribute, it works correctly, but I want to set up my column templates. I don't know how you got it to work in the demo site.

**Comment by MoonStorm** [comment]
Fixed in the master branch, currently holding the code for 3.1.0 RC. The data-* style attributes are supported, but the default templates do not use that notation. A full cleanup will occur in the next major release.
