### ISSUE TITLE
Controller 'trNgGrid', required by directive 'trNgGridPager', can't be found!

### ISSUE THREAD

**Issue by rondog** [MoonStorm/trNgGrid#56]
I am using `ui-router`. I have a `trNgTable` at `#/app/users` and it works great. On that same view I have a button that says `new user` which routes me to `#/app/users/new`. At this point, I get a bunch of exceptions in the console: https://docs.angularjs.org/error/$compile/ctreq?p0=trNgGrid&p1=trNgGridPager
![untitled-1](https://cloud.githubusercontent.com/assets/709057/3846827/2f622da0-1e60-11e4-92ea-73099d3bf05d.jpg)

Here is where my views are loaded:

     <div ui-view>
  
  	    
		<table tr-ng-grid="" items="users" page-items="10" selection-mode="none" class="table table-striped">
			<thead>
				<tr>
					<th field-name="username" display-name="Username" enable-filtering="false"></th>
					<th field-name="name" display-name="Name" enable-filtering="false"></th>
					<th field-name="client" display-name="Client" enable-filtering="false"></th>
					<th field-name="email" display-name="Email" enable-filtering="false"></th>
					<th field-name="phone" display-name="Phone" enable-filtering="false"></th>
					<th>
						<div class="tr-ng-title">Edit</div>
          </th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<a href="" class="center-block btn btn-default btn-xs" ng-click="">Edit</a>
					</td>
				</tr>
			</tbody>
		</table>

    </div>

Maybe I need to put the table outside of the `ui-view`

**Comment by MoonStorm** [comment]
One note before closing this one. Due to incompatibilities with Angular 1.3.15, I had to raise the minimum requirement for Angular to 1.3.1. :disappointed:
