### ISSUE TITLE
Custom filter implementation / combobox

### ISSUE THREAD

**Issue by bajak** [MoonStorm/trNgGrid#64]
Hallo,
thanks you for the great work. I really like MoonStorm.

I want to replace the filter textbox (input) with a combobox (select) of an column. Can not find any information to these topic. Should i replace the header and include my own solution? What about filtering for custom columns?

**Comment by MoonStorm** [comment]
Discussion moved to #12, where you'll also find a working sample based on @diego-vieira 's solution.
