### ISSUE TITLE
Custom date range column filter

### ISSUE THREAD

**Issue by britirie** [MoonStorm/trNgGrid#69]
I'm trying to figure if we can use trNgGrid with our AngularJS application but one of our requirements is to have our column date header to filter dates using a filter menu date range. I see examples using extJS and Kendo UI but nothing w/ trNgGrid. Can someone show me an example?

**Comment by MoonStorm** [comment]
Custom filtering #129 could solve this one for you. But not alone. You'll then have to hook up your date range to multiple values in the column filter #12.
