### ISSUE TITLE
Integration of Angular X-Editable

### ISSUE THREAD

**Issue by younes0** [MoonStorm/trNgGrid#7]
I didn't experiment yet with your lib, but it looks promising: how hard would you say it is to integrate editing features with  http://vitalets.github.io/angular-xeditable/#overview ?

**Comment by RamonBeast** [comment]
Same things here, could anybody find a workaround?
I can't use editable-form :(

**Comment by Evilcry** [comment]
Hello,
I'm trying to use x-editable on the latest version of trNgGrid but the tag editable-form throws a "Cannot read property '$data' of null" exception, before version 3 it was working fine, does somebody know how to make it work on version 3 too?

Thanks in advance.

**Comment by MoonStorm** [comment]
What exactly is `$ data` ?

The sooner someone posts a fiddle/plunke/anything, the quicker it's gonna get solved.

**Comment by SecondChance** [comment]
Here's a quick example of the problem.
[http://jsfiddle.net/cj9o2Lq5/](http://jsfiddle.net/cj9o2Lq5/)

**Comment by younes0** [comment]
So it looks like that X-Editable waits for `scope.$form.$data` which was provided by earlier versions of trNgGrid, what do you think?

**Comment by RamonBeast** [comment]
That might be it!

**Comment by MoonStorm** [comment]
@SecondChance How is that sample suppose to work when forms with the same name get created, one for each individual item?

**Comment by SecondChance** [comment]
@MoonStorm Yes one for each row. 

Check out the sample from x-editables site 
http://vitalets.github.io/angular-xeditable/#editable-row
or their fiddle
http://jsfiddle.net/NfPcH/93/

**Comment by Evilcry** [comment]
Hi MoonStorm,

Do you think you can solve the issue in the next release? 
otherwise is there any workaround you can suggest?

Thanks a lot for your hard work!

**Comment by RamonBeast** [comment]
I'm trying to figure out when it was removed, to check if I could port it back to at least to my local branch, but I am unable to find the moment when it was removed.

**Comment by MoonStorm** [comment]
Nothing was removed. You're looking at an example inspired from one of the samples from xeditable. For data binding, they use a ''$data'' variable, trNgGrid uses ''gridItem'' internally, so just replacing ''$data'' with ''gridItem'' you'll get SOMETHING working. But that's not the problem. The wrong form gets activated when you press on the ''edit'' button.

**Comment by RamonBeast** [comment]
Perfectly clear now, thanks a lot for taking the time to explain it!

**Comment by vtmoren** [comment]
I added ids to each of the row forms (per row) to get rid of the '$data' of null" error:
```
           <tbody>
                    <tr>
                        <td field-name="first">
                            <span editable-text="gridItem.first" e-name="first" e-form="rowForm_{{gridItem.id}}" e-required>
                                {{gridItem.first}}
                           </span>
                        </td>
                        <td field-name="last">
                            <span editable-text="gridItem.last" e-name="last" e-form="rowForm_{{gridItem.id}}" e-required>
                                {{gridItem.last}}
                            </span>
                        </td>
                        <td>
                            <!-- form -->
                            <form editable-form name="rowForm_{{gridItem.id}}" ng-show="rowForm.$visible" class="form-buttons form-inline">
                                <button type="submit" ng-disabled="rowForm.$waiting" class="btn btn-primary btn-xs">
                                    Save
                                </button>
                                <button type="button" ng-disabled="rowForm.$waiting" ng-click="rowForm.$cancel" class="btn btn-default btn-xs">
                                    Cancel
                                </button>
                            </form>
                            <div class="buttons" ng-show="!rowForm.$visible">
                                <button class="btn btn-default btn-xs" ng-click="displaySaveForm">Edit</button>
                                <button class="btn btn-danger btn-xs" ng-click="deleteUser($index)">Delete</button>
                            </div>
                        </td>
                    </tr>
                </tbody>
```

I need to do the same with the .$visible, $waiting, $cancel variables.  How do I do that?

**Comment by MoonStorm** [comment]
To be honest with you, I don't know. It looks like too much hacking for my taste. I'd just open up a  dialog, hook up nicely the editor to the entity over there:

http://angular-ui.github.io/bootstrap/

The moment we got support for multiple rows in the grid defintion, another option would be to display the editor on its own, on an expanded row with colspaned cells.

**Comment by RamonBeast** [comment]
@MoonStorm so for now the best way would be the one you are suggesting I think.

Do you know if there will be full support for x-editable, and if so, do you have any timeframe for that? Not to pressure you of course, just to optimize my development.

Thank you for all the help you have provided so far!

**Comment by MoonStorm** [comment]
I won't have time to look into making it x-editable friendly until finishing up the next release, which will allow for DOM modifying directives inside the table definition, and this alone requires a huge effort.

**Comment by Solimen** [comment]
+1 for this feature!

**Comment by TrustNoOne** [comment]
+1!

**Comment by RamonBeast** [comment]
+1 from me too.

As usual thank you @MoonStorm.

**Comment by N3mes1s** [comment]
same here, +1. thanks

**Comment by Raff0** [comment]
+1!!!!!!

**Comment by MoonStorm** [comment]
I just pushed a change to the grid that allows for limited support of directives on the TR elements, enough to allow us to use X-Editable. The code is on the ``master`` branch. [Here is the fiddle](http://jsfiddle.net/MoonStorm/mckckkf2/).

**Comment by RamonBeast** [comment]
Hi @MoonStorm,
thanks for the *MUCH* appreciated update!!!!

I'm right now working on the integration and testing, I've seen that directives like ng-* are not supported, what about the e-ng-options? I'm trying to create an editable row that has a select box but I get the "TypeError: Cannot read property '$data' of null" error. Is that unsupported too?

Thank you!!
