### ISSUE TITLE
Initial sorting

### ISSUE THREAD

**Issue by Eraindil** [MoonStorm/trNgGrid#76]
Is there a way to enable an initial sorting on one are more collumns?

The order-by doesn't work.

**Comment by jamescarter-le** [comment]
I have found that if you provide the initial results as sorted, they do not appear in the same order on this.

How can we fix this?

**Comment by MoonStorm** [comment]
All these issues should be fixed in 3.0.4

The order of the initial items is now maintained, and the ``order-by`` attribute will work even if set prior the items getting bound to the grid.

http://moonstorm.github.io/trNgGrid/release/#/TestItemsUpdate
