### ISSUE TITLE
Change column filter to be based on beginning letters

### ISSUE THREAD

**Issue by joejet2222** [MoonStorm/trNgGrid#77]
Perhaps best explained by an example....

List items in column:
Apple
Banana
Cherry

Current filtering -- if I type in 'a', Apple and Banana remain because both contain an 'a' in the word.

Proposed filtering - if I type in 'a', have only Apple remaining because it begins with 'a'

Is this something I would need to modify in the code directly?  While I found both ngGrid and ngTable to be unusable for my purposes, their column filtering seem to be based on beginning letters.

**Comment by MoonStorm** [comment]
Custom column filters are on the horizon.

#129
