### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by escapismc** [MoonStorm/trNgGrid#82]
Is it possible to have a mode that enables the text to be selectable for copy & paste?  It seems like the highlight/selection functionality is preventing this, even if I set the selection-mode to none.

**Comment by varmeEqualsthis** [comment]
Just a small change to the above css by carueda : add !important to override the default style.

**Comment by jdforsythe** [comment]
Note, if you want this globally (i.e. you don't use tables with selectable rows), you can use:

```css
table.tr-ng-grid > tbody > tr > td,
table.tr-ng-grid > tbody > tr > td > .tr-ng-cell {
    -webkit-user-select: text !important;
    -moz-user-select: text !important;
    -ms-user-select: text !important;
    user-select: text !important;
}```
