### ISSUE TITLE
Dynamic row background color

### ISSUE THREAD

**Issue by nickiewooster** [MoonStorm/trNgGrid#83]
Hi
Im new with Trnggrid and right now im trying to make my table rows to have a color based on an attribute in the row data. Is there a simpler way to achieve this other than redefining each <td> cell within each row using the field-name ?

**Comment by MoonStorm** [comment]
The code for this feature was pushed to the ``master`` branch. There is a sample in the ``Customizations/Per Instance`` section on the demo site.
