### ISSUE TITLE
display-format-html

### ISSUE THREAD

**Issue by carueda** [MoonStorm/trNgGrid#84]
I often use filters that generate html and, currently, I handle this by explicitly using the `ng-bind-html` mechanism within an explicit `<tbody> ...` in the table. Not too bad, but it would be nice to have a `display-format-html` (or whatever other name) option that does this for me.  Thanks!

**Comment by MoonStorm** [comment]
Finally!

@panuhorsmalahti , thanks for keeping me up-to-date.

(That still doesn't mean I agree with an attribute containing HTML or an Angular filter returning similar content)
