### ISSUE TITLE
Eanble Disable Global Filter without showing column Filters

### ISSUE THREAD

**Issue by spsenthil** [MoonStorm/trNgGrid#86]
Presently, 
 enable-filtering="false" will disable both column filters as well as Global Filter.
Expected:
Could we provide options to 
1. enable/disable column filters 
   2.enable/disable global filter

**Comment by olefredrik** [comment]
Putting ```enable-filtering="false"``` in the table ```div``` will disable all column filters. No need to put it in every single column.

**Comment by hassanwasef** [comment]
Hello Moon storm, 
I would like to remove the Global Filter TextBox from the grid's footer.
Is there a way to do that without removing both of them.. 
Thank you very much for that wonderful grid.

**Comment by MoonStorm** [comment]
``enable-filtering="false"`` on the grid itself and ``enable-filtering="true"`` in each column definition.

**Comment by hexamindtechnologies** [comment]
How do I user external controls for filtering ??
