### ISSUE TITLE
How to save grid state across pages without using server-side code ?

### ISSUE THREAD

**Issue by pastanislas** [MoonStorm/trNgGrid#87]
Hello, I'm trying to pass grid state across another controller but I can't figure how to get necesary variable.
I've try to saved 
`{{ TrNgGrid.filterByDisplayFields }}`
`{{ columnOptions.filter }}`
`{{ filterByDisplayFields }}`

but none of these seems to work.
The idea is to restore the grid state when a user click the back button ie
* ` <a ng-click=goBacktoSavedGrid(filters, pages, globalfilter, sort)>back</a>`

Thank you for your help.
Ps : this plugin is awesome !

**Comment by MoonStorm** [comment]
``filter-by-fields`` is now linked two-way. I have also updated the ``Configuration`` and the ``Server Side`` page on the demo site with samples.
