### ISSUE TITLE
Replace/insert option for column header transclusion

### ISSUE THREAD

**Issue by MoonStorm** [MoonStorm/trNgGrid#93]
The grid currently detects HTML elements (but not just text content) inside the TH elements, using them instead of its own content. When it sees HTML children in the TH, it's turning off its header generation for that particular column. This allows one to provide the entire content of a header cell. Problem is, in this mode, you need to manually include the other inner directives of the grid in there, such as the filtering and the sorting directive, if indeed you want them there (you might not). Which is not ideal, reason why I refrained from including samples with this approach in there. I might post a couple if there is demand for it.

So as you can see, there is no middle ground at the moment, you either have a simple text title or a fully customized column header. You can't have HTML as a title, which gets included in the right spot in the default rendered cell content in the header (i.e. what we're discussing here). If you check the code, and you'll find the template for the header cell with ease (at the end of the file), you can see the `ng-transclude` directive used in two different ways, based on a flag that indicates whether the cell is customized or not.

**Comment by jasonwlindsay** [comment]
I would love to see an example of manually referencing the sorting and filtering directives.  I am trying to get some custom HTML working inside the table header cells, and the only thing my solution is the sorting chevron.

Could you/would you please be willing to provide an example of a custom table header calling those directives?

**Comment by MoonStorm** [comment]
The discussion in #12 might touch on what you're after. You basically have to manually set the directives, same as the default template does. You can find the template at the end of the source file and get some inspiration from there.
