### ISSUE TITLE
Filtering is broken when using only custom columns.

### ISSUE THREAD

**Issue by khronnuz** [MoonStorm/trNgGrid#96]
I needed to use custom columns(no field-name) for all columns in some pages, on those pages when I type something on search field, all items disappear. If I remove the text on the filter box, the items do NOT appear back.

**Comment by MoonStorm** [comment]
As I probably mentioned before, "Computed Fields" with an angular filter or customizing the body cell for an existing field will do the trick. The demo site has examples inside the ``Columns`` section, and I also added a test case for ``x-editable``. Let me know if you guys still experience issues.
